<?php
namespace App\Services;
use App\Models\{AcademicPeriod,Assessment,AuditLog,Grade,ReportCard};use Illuminate\Support\Facades\DB;
final class AssessmentLifecycleService {
 public function open(Assessment $a,int $user):void{DB::transaction(function()use($a,$user){$x=Assessment::whereKey($a->id)->lockForUpdate()->firstOrFail();abort_unless($x->status==='draft',422,'Only draft assessments can be opened.');$x->update(['status'=>'open']);$this->audit($user,$x,'assessment.opened','Assessment opened for grade entry');});}
 public function complete(Assessment $a,int $user):array{$rows=$this->counts($a);if($rows['invalid'])return ['ok'=>false,'counts'=>$rows,'errors'=>['Invalid grades exist.']];DB::transaction(function()use($a,$user){$x=Assessment::whereKey($a->id)->lockForUpdate()->firstOrFail();abort_unless(in_array($x->status,['draft','open'],true),422,'Only an open assessment can be completed.');$x->update(['status'=>'completed','completed_at'=>now(),'completed_by'=>$user]);$this->audit($user,$x,'assessment.completed','Assessment completed');});return ['ok'=>true,'counts'=>$rows];}
 public function lock(Assessment $a,int $user):void{DB::transaction(function()use($a,$user){$x=Assessment::whereKey($a->id)->lockForUpdate()->firstOrFail();abort_unless($x->status==='completed',422,'Only completed assessments can be locked.');$x->update(['status'=>'locked','locked_at'=>now(),'locked_by'=>$user]);$this->audit($user,$x,'assessment.locked','Assessment locked');});}
 public function publish(Assessment $a,int $user):void{DB::transaction(function()use($a,$user){$x=Assessment::whereKey($a->id)->lockForUpdate()->firstOrFail();abort_unless($x->status==='locked',422,'Only locked assessments can be published.');$x->update(['published_at'=>now(),'published_by'=>$user]);$this->audit($user,$x,'assessment.published','Assessment results published to parents');});}
 public function reopen(Assessment $a,int $user,string $reason):void{abort_unless(trim($reason)!=='',422,'A reopening reason is required.');DB::transaction(function()use($a,$user,$reason){$x=Assessment::whereKey($a->id)->lockForUpdate()->firstOrFail();abort_if($x->status==='draft',422,'Assessment is already editable.');$old=$x->status;$x->update(['status'=>'open','published_at'=>null,'published_by'=>null,'reopened_at'=>now(),'reopened_by'=>$user,'reopen_reason'=>$reason]);$this->audit($user,$x,'assessment.reopened',$reason,['status'=>$old],['status'=>'open','reason'=>$reason]);});}
 public function auditGrade(Grade $grade,int $user,?array $old,string $reason=null):void{$this->audit($user,$grade,'grade.changed',$reason??'Grade changed',$old??[],$grade->only(['value','status','comment','student_academic_enrollment_id']));$assessment=$grade->assessment;$number=AcademicPeriod::whereKey($assessment->academic_period_id)->value('number');$key=[1=>'trimester_1',2=>'trimester_2',3=>'trimester_3'][$number]??null;if($key)ReportCard::where('tenant_id',$grade->tenant_id)->where('student_academic_enrollment_id',$grade->student_academic_enrollment_id)->where('academic_year_id',$assessment->academic_year_id)->where('period_key',$key)->update(['source_data_changed'=>true]);}
 public function counts(Assessment $a):array{$total=$a->groups()->withCount(['academicEnrollments'=>fn($q)=>$q->where('academic_year_id',$a->academic_year_id)->where('school_level_id',$a->school_level_id)])->get()->sum('academic_enrollments_count');$grades=$a->grades()->get();$graded=$grades->where('status','graded')->count();$absent=$grades->whereIn('status',['absent','absent_with_zero'])->count();$exempted=$grades->where('status','exempted')->count();return ['total'=>$total,'graded'=>$graded,'absent'=>$absent,'exempted'=>$exempted,'not_graded'=>max($total-$graded-$absent-$exempted,0),'invalid'=>$grades->filter(fn($g)=>$g->status==='graded'&&($g->value===null||$g->value<0||$g->value>$a->maximum_grade))->count()];}
 private function audit(int $user,$related,string $event,string $description,array $old=[],array $new=[]):void{AuditLog::create(['user_id'=>$user,'event'=>$event,'related_type'=>$related::class,'related_id'=>$related->id,'description'=>$description,'old_values'=>$old,'new_values'=>$new,'occurred_at'=>now()]);}
}
