<?php
namespace App\Services;
use App\Models\{AuditLog,ReportCard};
use Illuminate\Support\Facades\DB;
final class ReportCardValidationService {
 public function readiness(ReportCard $card): array { $card->loadMissing(['enrollment','subjects']); $errors=[];$warnings=[]; if(!$card->generated_at)$errors[]=['code'=>'not_calculated','message'=>'Le bulletin n’a pas été généré.']; if(!$card->enrollment || $card->enrollment->academic_year_id!==$card->academic_year_id || $card->enrollment->student_id!==$card->student_id)$errors[]=['code'=>'invalid_enrollment','message'=>'Inscription académique incohérente.']; if($card->period_key==='annual'){if($card->general_average===null)$errors[]=['code'=>'missing_annual_average','message'=>'La moyenne annuelle n’a pas encore été calculée.'];return ['ready'=>!$errors,'blocking_errors'=>$errors,'warnings'=>$warnings];} foreach($card->subjects as $s){if((float)$s->coefficient<=0)$errors[]=['code'=>'coefficient','subject_id'=>$s->subject_id,'message'=>"Coefficient invalide pour {$s->subject_name}."]; if($s->average===null&&!$s->is_exempted&&!$s->is_informational)$errors[]=['code'=>'missing_result','subject_id'=>$s->subject_id,'message'=>"Résultat manquant pour {$s->subject_name}."]; if(!$s->teacher_id)$warnings[]=['code'=>'teacher','subject_id'=>$s->subject_id,'message'=>"Enseignant absent pour {$s->subject_name}."];} return ['ready'=>!$errors,'blocking_errors'=>$errors,'warnings'=>$warnings]; }
 public function validate(ReportCard $card, int $userId): array { $r=$this->readiness($card); if(!$r['ready'])return $r; DB::transaction(function()use($card,$userId){$locked=ReportCard::whereKey($card->id)->lockForUpdate()->firstOrFail(); if($locked->status!=='draft')return; $locked->update(['status'=>'validated','validated_at'=>now(),'validated_by'=>$userId]); AuditLog::create(['user_id'=>$userId,'event'=>'report_card.validated','related_type'=>ReportCard::class,'related_id'=>$locked->id,'description'=>'Bulletin validé','new_values'=>['status'=>'validated'],'occurred_at'=>now()]);}); return ['ready'=>true,'blocking_errors'=>[],'warnings'=>$r['warnings']]; }
 public function transition(ReportCard $card,string $status,int $userId,?string $reason=null): void { DB::transaction(function()use($card,$status,$userId,$reason){$c=ReportCard::whereKey($card->id)->lockForUpdate()->firstOrFail(); $allowed=match($status){ 'published'=>$c->status==='validated','locked'=>in_array($c->status,['published','validated']), 'draft'=>in_array($c->status,['validated','published','locked']), default=>false}; if(!$allowed)abort(422,'Transition de statut invalide.'); if($status==='draft'&&!$reason)abort(422,'Une raison est obligatoire pour rouvrir.'); $old=$c->status; $data=['status'=>$status]; if($status==='published')$data+=['published_at'=>now(),'published_by'=>$userId]; if($status==='locked')$data+=['locked_at'=>now(),'locked_by'=>$userId]; if($status==='draft')$data+=['validated_at'=>null,'validated_by'=>null]; $c->update($data); $description=$reason??match($status){'published'=>'Bulletin publié','locked'=>'Bulletin verrouillé',default=>'Bulletin rouvert'}; AuditLog::create(['user_id'=>$userId,'event'=>'report_card.'.($status==='draft'?'reopened':$status),'related_type'=>ReportCard::class,'related_id'=>$c->id,'description'=>$description,'old_values'=>['status'=>$old],'new_values'=>$data,'occurred_at'=>now()]); }); }
}
