<script setup lang="ts">
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { appConfirm, appPrompt } from '@/composables/useAppDialog';
import { router, useForm } from '@inertiajs/vue3';
import { computed, ref } from 'vue';

const props=defineProps<{employee:any;category:string;definition:any}>();
const search=ref(''); const showArchived=ref(false);
const form=useForm({category:props.category,type:Object.keys(props.definition.types)[0]||'',title:'',reference:'',starts_at:'',ends_at:'',status:Object.keys(props.definition.statuses)[0]||'',score:'',amount:'',description:'',is_confidential:['discipline','note','evaluation'].includes(props.category),metadata:{provider:'',location:'',evaluator:'',objectives:'',severity:'',follow_up_date:'',justification:'',probation_end:''}});
const records=computed(()=>props.employee.hr_records?.filter((r:any)=>r.category===props.category&&(showArchived.value||!r.archived_at)&&(!search.value||`${r.title} ${r.reference||''} ${r.description||''}`.toLowerCase().includes(search.value.toLowerCase())))||[]);
const needsScore=computed(()=>props.category==='evaluation'); const needsAmount=computed(()=>['contract','training'].includes(props.category));
const submit=()=>form.post(`/admin/staff/${props.employee.id}/hr-records`,{preserveScroll:true,onSuccess:()=>{form.reset();form.category=props.category;form.type=Object.keys(props.definition.types)[0];form.status=Object.keys(props.definition.statuses)[0];form.is_confidential=['discipline','note','evaluation'].includes(props.category);}});
const changeStatus=async(record:any)=>{const status=await appPrompt('Choisissez le nouveau statut parmi :\n'+Object.entries(props.definition.statuses).map(([key,label])=>`${key} — ${label}`).join('\n'),{title:'Changer le statut',inputLabel:'Code du statut',inputPlaceholder:Object.keys(props.definition.statuses).join(', '),inputRequired:true,inputValue:record.status,confirmText:'Mettre à jour'});if(status&&props.definition.statuses[status])router.patch(`/admin/staff/${props.employee.id}/hr-records/${record.id}/status`,{status},{preserveScroll:true});};
const archive=async(record:any)=>{if(await appConfirm('La fiche sera retirée de la vue active mais restera conservée dans le dossier et son historique.',{title:'Archiver cette fiche ?',confirmText:'Archiver',tone:'warning'}))router.patch(`/admin/staff/${props.employee.id}/hr-records/${record.id}/archive`,{},{preserveScroll:true});};
const date=(v:string)=>v?new Intl.DateTimeFormat('fr-DZ').format(new Date(`${v.substring(0,10)}T00:00:00`)):'—';
</script>
<template><section class="space-y-6">
 <div class="grid gap-3 sm:grid-cols-3"><div class="rounded-xl border bg-card p-4"><p class="text-sm text-muted-foreground">Fiches actives</p><b class="text-2xl">{{employee.hr_records?.filter((r:any)=>r.category===category&&!r.archived_at).length||0}}</b></div><div class="rounded-xl border bg-card p-4"><p class="text-sm text-muted-foreground">Finalisées / clôturées</p><b class="text-2xl">{{employee.hr_records?.filter((r:any)=>r.category===category&&['completed','closed','acknowledged','resolved','expired','terminated'].includes(r.status)).length||0}}</b></div><div class="rounded-xl border bg-card p-4"><p class="text-sm text-muted-foreground">Confidentielles</p><b class="text-2xl">{{employee.hr_records?.filter((r:any)=>r.category===category&&r.is_confidential).length||0}}</b></div></div>
 <form class="rounded-xl border bg-card p-5" @submit.prevent="submit"><h2 class="font-semibold">Ajouter — {{definition.label}}</h2><div class="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><div><Label>Type *</Label><select v-model="form.type" class="mt-1 h-9 w-full rounded-md border bg-background px-3"><option v-for="(label,key) in definition.types" :key="key" :value="key">{{label}}</option></select></div><div><Label>Intitulé *</Label><Input v-model="form.title" required/></div><div><Label>Référence</Label><Input v-model="form.reference"/></div><div><Label>Statut *</Label><select v-model="form.status" class="mt-1 h-9 w-full rounded-md border bg-background px-3"><option v-for="(label,key) in definition.statuses" :key="key" :value="key">{{label}}</option></select></div><div><Label>Date de début</Label><Input v-model="form.starts_at" type="date"/></div><div><Label>Date de fin / échéance</Label><Input v-model="form.ends_at" type="date"/></div><div v-if="needsScore"><Label>Score / 100</Label><Input v-model="form.score" type="number" min="0" max="100" step="0.5"/></div><div v-if="needsAmount"><Label>{{category==='training'?'Coût':'Montant de référence'}}</Label><Input v-model="form.amount" type="number" min="0" step="0.01"/></div><div v-if="category==='training'"><Label>Organisme</Label><Input v-model="form.metadata.provider"/></div><div v-if="category==='training'"><Label>Lieu</Label><Input v-model="form.metadata.location"/></div><div v-if="category==='evaluation'"><Label>Évaluateur</Label><Input v-model="form.metadata.evaluator"/></div><div v-if="category==='evaluation'"><Label>Objectifs suivants</Label><Input v-model="form.metadata.objectives"/></div><div v-if="category==='discipline'"><Label>Niveau / gravité</Label><Input v-model="form.metadata.severity" placeholder="Faible, moyen, élevé..."/></div><div v-if="category==='absence'"><Label>Justificatif</Label><Input v-model="form.metadata.justification"/></div><div v-if="category==='contract'"><Label>Fin période d’essai</Label><Input v-model="form.metadata.probation_end" type="date"/></div><div v-if="category==='note'"><Label>Date de suivi</Label><Input v-model="form.metadata.follow_up_date" type="date"/></div><div class="md:col-span-2 lg:col-span-4"><Label>Description / détails</Label><textarea v-model="form.description" class="mt-1 min-h-24 w-full rounded-md border bg-background p-3"/></div><label class="flex items-center gap-2"><input v-model="form.is_confidential" type="checkbox"/> Fiche confidentielle</label></div><div v-if="Object.keys(form.errors).length" class="mt-3 rounded-md bg-destructive/10 p-3 text-sm text-destructive"><p v-for="error in form.errors" :key="error">{{error}}</p></div><Button class="mt-4" :disabled="form.processing">Enregistrer la fiche</Button></form>
 <div class="rounded-xl border bg-card p-5"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 class="font-semibold">Historique — {{definition.label}}</h2><div class="flex gap-2"><Input v-model="search" placeholder="Rechercher dans les fiches..."/><label class="flex shrink-0 items-center gap-2 text-xs"><input v-model="showArchived" type="checkbox"/> Archives</label></div></div><div v-if="records.length" class="mt-4 grid gap-3 lg:grid-cols-2"><article v-for="record in records" :key="record.id" class="rounded-xl border p-4" :class="{'opacity-60':record.archived_at}"><div class="flex items-start justify-between gap-2"><div><div class="flex flex-wrap items-center gap-2"><b>{{record.title}}</b><span class="rounded-full bg-primary/10 px-2 py-0.5 text-xs text-primary">{{definition.types[record.type]}}</span><span v-if="record.is_confidential" class="rounded-full bg-amber-100 px-2 py-0.5 text-xs text-amber-800">Confidentiel</span></div><p class="text-sm text-muted-foreground">{{record.reference||'Sans référence'}} · {{definition.statuses[record.status]||record.status}}</p></div><span v-if="record.score!==null" class="text-lg font-bold">{{Number(record.score)}}/100</span></div><p v-if="record.starts_at||record.ends_at" class="mt-3 text-sm">{{date(record.starts_at)}} → {{date(record.ends_at)}}</p><p v-if="record.description" class="mt-2 text-sm whitespace-pre-line text-muted-foreground">{{record.description}}</p><div class="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" :disabled="!!record.archived_at" @click="changeStatus(record)">Changer le statut</Button><Button v-if="!record.archived_at" size="sm" variant="ghost" @click="archive(record)">Archiver</Button></div><details v-if="record.events?.length" class="mt-3 text-xs text-muted-foreground"><summary class="cursor-pointer">Journal ({{record.events.length}})</summary><p v-for="event in record.events" :key="event.id" class="mt-1">{{event.created_at}} — {{event.actor?.name||'Système'}} : {{event.event}}</p></details></article></div><p v-else class="mt-4 text-sm text-muted-foreground">Aucune fiche dans cette section.</p></div>
</section></template>
