<!doctype html><html lang="fr"><head><meta charset="utf-8"><style>
@page{margin:28px}body{font-family:DejaVu Sans,sans-serif;color:#17202a;font-size:10px;line-height:1.4}h1{margin:0;font-size:24px;color:#123f5a}h2{margin:22px 0 8px;font-size:14px;color:#123f5a}.header{border-bottom:3px solid #159a8c;padding-bottom:14px}.muted{color:#64748b}.identity{margin-top:14px;padding:12px;background:#f1f7f6;border-left:4px solid #159a8c}.identity strong{font-size:14px}table{width:100%;border-collapse:collapse}th{padding:7px 6px;background:#123f5a;color:#fff;font-size:9px;text-align:left}td{padding:7px 6px;border-bottom:1px solid #dce4e8;vertical-align:top}tbody tr:nth-child(even){background:#f7fafb}.right{text-align:right}.center{text-align:center}.nowrap{white-space:nowrap}.summary{margin-top:18px;margin-left:42%;width:58%}.summary td{padding:6px 8px}.summary .net td{background:#123f5a;color:#fff;font-size:13px;font-weight:bold}.badge{display:inline-block;padding:2px 5px;background:#dff4ef;color:#08766b}.footer{margin-top:24px;padding-top:10px;border-top:1px solid #dce4e8;color:#64748b;font-size:8px}
</style></head><body>
<div class="header"><h1>Bulletin de salaire</h1><div class="muted">{{ $statement->reference }} · Période du {{ $statement->period_start->format('d/m/Y') }} au {{ $statement->period_end->format('d/m/Y') }}</div></div>
<div class="identity"><strong>{{ $statement->staff->name }}</strong><br>Matricule {{ $statement->staff->employee_code }} · {{ $statement->staff->employeeType->name }}<br>Configuration : {{ $statement->configuration?->name ?? 'Configuration archivée' }} · {{ number_format((float)$statement->base_rate,2,',',' ') }} {{ $currency }}</div>
<h2>Détail des heures et séances validées</h2>
@if($statement->teacherAttendances->isNotEmpty())
<table><thead><tr><th>Date</th><th>Formation / niveau</th><th>Séance / groupe</th><th>Horaire</th><th>Formateur</th><th class="right">Durée</th><th>Statut</th></tr></thead><tbody>
@foreach($statement->teacherAttendances->sortBy('session.starts_at') as $attendance)
@php($session=$attendance->session)
<tr><td class="nowrap">{{ $session->starts_at->format('d/m/Y') }}</td><td>{{ $session->group?->plan?->course?->title ?? '—' }}<br><span class="muted">{{ $session->group?->plan?->level?->name ?? '' }}</span></td><td>{{ $session->title }}<br><span class="muted">{{ $session->group?->name ?? '—' }}</span></td><td class="nowrap">{{ $session->starts_at->format('H:i') }} – {{ $session->ends_at->format('H:i') }}</td><td>{{ $attendance->actualTeacher?->name ?? '—' }}@if($attendance->actual_teacher_id!==$attendance->scheduled_teacher_id)<br><span class="muted">Prévu : {{ $attendance->scheduledTeacher?->name }}</span>@endif</td><td class="right nowrap"><strong>{{ intdiv($attendance->worked_minutes,60) }}h {{ str_pad((string)($attendance->worked_minutes%60),2,'0',STR_PAD_LEFT) }}</strong></td><td><span class="badge">{{ match($attendance->status){'present'=>'Présent','late'=>'Retard','replaced'=>'Remplacé',default=>ucfirst($attendance->status)} }}</span></td></tr>
@endforeach
</tbody><tfoot><tr><td colspan="5"><strong>Total validé</strong></td><td class="right"><strong>{{ intdiv($statement->teacherAttendances->sum('worked_minutes'),60) }}h {{ str_pad((string)($statement->teacherAttendances->sum('worked_minutes')%60),2,'0',STR_PAD_LEFT) }}</strong></td><td>{{ $statement->teacherAttendances->count() }} séance(s)</td></tr></tfoot></table>
@else<div class="identity">Ce bulletin ne repose pas sur des séances d’enseignement détaillées.</div>@endif
<table class="summary"><tr><td>Mode de calcul</td><td class="right">{{ match($statement->salary_type->value){'monthly'=>'Mensuel','hourly'=>'Horaire','per_session'=>'Par séance','daily'=>'Journalier','custom'=>'Manuel'} }} · {{ $statement->units }} unité(s)</td></tr><tr><td>Salaire brut</td><td class="right">{{ number_format((float)$statement->gross_salary,2,',',' ') }} {{ $currency }}</td></tr><tr><td>Primes, exceptionnel, remboursements</td><td class="right">+ {{ number_format((float)$statement->bonuses+(float)$statement->exceptional_payments+(float)$statement->reimbursements,2,',',' ') }} {{ $currency }}</td></tr><tr><td>Déductions et avances</td><td class="right">- {{ number_format((float)$statement->deductions+(float)$statement->advances,2,',',' ') }} {{ $currency }}</td></tr><tr class="net"><td>Net à payer</td><td class="right">{{ number_format((float)$statement->net_salary,2,',',' ') }} {{ $currency }}</td></tr><tr><td>Payé</td><td class="right">{{ number_format((float)$statement->amount_paid,2,',',' ') }} {{ $currency }}</td></tr><tr><td>Reste</td><td class="right">{{ number_format((float)$statement->remaining_amount,2,',',' ') }} {{ $currency }}</td></tr></table>
<h2>Historique des paiements</h2><table><thead><tr><th>Date</th><th>Référence</th><th>Méthode</th><th class="right">Montant</th></tr></thead><tbody>@forelse($statement->payments as $payment)<tr><td>{{ $payment->paid_at->format('d/m/Y') }}</td><td>{{ $payment->reference }}</td><td>{{ $payment->payment_method }}</td><td class="right">{{ number_format((float)$payment->amount,2,',',' ') }} {{ $currency }}</td></tr>@empty<tr><td colspan="4" class="center muted">Aucun paiement enregistré.</td></tr>@endforelse</tbody></table>
<div class="footer">Document généré le {{ now()->format('d/m/Y à H:i') }}. Les heures affichées proviennent des présences enseignantes validées et réservées à ce bulletin.</div>
</body></html>
