<!doctype html><html lang="fr"><head><meta charset="utf-8"><style>
@page{margin:24px 30px}body{font-family:DejaVu Sans,sans-serif;color:#17202a;font-size:10px;line-height:1.35}.header{display:table;width:100%;border-bottom:3px solid #123f5a;padding-bottom:12px}.brand,.title{display:table-cell;vertical-align:middle}.brand{width:62%}.title{text-align:right}.logo{max-height:58px;max-width:115px;float:left;margin-right:12px}h1{margin:0;font-size:22px;color:#123f5a}h2{margin:0 0 3px;font-size:15px}.muted{color:#64748b}.employee{margin:14px 0;display:table;width:100%;border:1px solid #cbd5e1;background:#f8fafc}.employee>div{display:table-cell;width:50%;padding:9px 12px}.label{font-size:8px;text-transform:uppercase;color:#64748b}.value{font-weight:bold;margin-bottom:6px}table{width:100%;border-collapse:collapse}th{padding:7px 6px;background:#123f5a;color:#fff;font-size:9px;text-align:left;text-transform:uppercase}td{padding:7px 6px;border-bottom:1px solid #dce4e8}tbody tr:nth-child(even){background:#f7fafb}.right{text-align:right}.center{text-align:center}.summary{margin-top:16px;margin-left:48%;width:52%}.summary td{padding:6px 8px}.summary .net td{background:#123f5a;color:#fff;font-size:14px;font-weight:bold;border:0}.footer{position:fixed;bottom:0;left:0;right:0;border-top:1px solid #cbd5e1;padding-top:7px;color:#64748b;font-size:8px;text-align:center}
</style></head><body>
<div class="header"><div class="brand">
@if($school->logo_url)<img class="logo" src="{{ public_path(ltrim(parse_url($school->logo_url, PHP_URL_PATH), '/')) }}">@endif
<h2>{{ $school->legal_name ?: $school->trading_name }}</h2><div>{{ collect([$school->address_line_1,$school->address_line_2,$school->postal_code,$school->city])->filter()->join(', ') }}</div><div>{{ collect([$school->phone,$school->email])->filter()->join(' · ') }}</div>
@if($school->registration_number || $school->tax_number)<div class="muted">@if($school->registration_number)RC / NIS : {{ $school->registration_number }}@endif @if($school->tax_number) · NIF : {{ $school->tax_number }}@endif</div>@endif
</div><div class="title"><h1>Bulletin de paie</h1><div class="muted">Période {{ $statement->period_start->translatedFormat('F Y') }}</div></div></div>
<div class="employee"><div><div class="label">Nom et prénom</div><div class="value">{{ $statement->staff->name }}</div><div class="label">Matricule</div><div class="value">{{ $statement->staff->employee_code ?: '—' }}</div></div><div><div class="label">Fonction / Poste</div><div class="value">{{ $statement->staff->employeeType?->name ?: '—' }}</div><div class="label">Numéro CNAS</div><div class="value">{{ $statement->staff->social_security_number ?: '—' }}</div></div></div>
<table><thead><tr><th>Rubrique</th><th class="right">Base / Qté</th><th class="right">Taux</th><th class="right">Gain</th><th class="right">Retenue</th></tr></thead><tbody>
@forelse($statement->lines as $line)<tr><td>{{ $line->item_name }}</td><td class="right">{{ $line->calculation_type->value === 'HOURLY' ? number_format((float)$line->quantity,2,',',' ').' h' : number_format((float)$line->quantity,2,',',' ') }}</td><td class="right">{{ $line->rate !== null ? number_format((float)$line->rate,2,',',' ').' '.$currency : '—' }}</td><td class="right">{{ (float)$line->amount > 0 ? number_format((float)$line->amount,2,',',' ').' '.$currency : '—' }}</td><td class="right">{{ (float)$line->amount < 0 ? number_format(abs((float)$line->amount),2,',',' ').' '.$currency : '—' }}</td></tr>@empty<tr><td colspan="5" class="center muted">Aucune ligne de salaire.</td></tr>@endforelse
@foreach($statement->statutoryLines->where('affects_net',true) as $line)<tr><td>{{ $line->label }}</td><td class="right">{{ number_format((float)$line->base,2,',',' ') }}</td><td class="right">{{ $line->rate !== null ? number_format((float)$line->rate*100,2,',',' ').' %' : 'Barème' }}</td><td class="right">—</td><td class="right">{{ number_format((float)$line->amount,2,',',' ') }} {{ $currency }}</td></tr>@endforeach
</tbody></table>
<table class="summary"><tr><td>Salaire brut</td><td class="right">{{ number_format((float)$statement->gross_salary+(float)$statement->bonuses+(float)$statement->exceptional_payments+(float)$statement->reimbursements,2,',',' ') }} {{ $currency }}</td></tr><tr><td>Assiette CNAS</td><td class="right">{{ number_format((float)$statement->cnas_base,2,',',' ') }} {{ $currency }}</td></tr><tr><td>CNAS salarié</td><td class="right">{{ number_format((float)$statement->employee_cnas,2,',',' ') }} {{ $currency }}</td></tr><tr><td>Base imposable IRG</td><td class="right">{{ number_format((float)$statement->irg_base,2,',',' ') }} {{ $currency }}</td></tr><tr><td>IRG</td><td class="right">{{ number_format((float)$statement->irg_amount,2,',',' ') }} {{ $currency }}</td></tr><tr><td>Autres retenues</td><td class="right">{{ number_format((float)$statement->deductions+(float)$statement->advances,2,',',' ') }} {{ $currency }}</td></tr><tr class="net"><td>NET À PAYER</td><td class="right">{{ number_format((float)$statement->net_salary,2,',',' ') }} {{ $currency }}</td></tr><tr><td>Charges employeur</td><td class="right">{{ number_format((float)$statement->employer_contributions,2,',',' ') }} {{ $currency }}</td></tr><tr><td>Coût total employeur</td><td class="right">{{ number_format((float)$statement->total_employer_cost,2,',',' ') }} {{ $currency }}</td></tr></table>
@if($statement->notes)<p><strong>Observations :</strong> {{ $statement->notes }}</p>@endif<div class="footer">Bulletin de paie — {{ $school->legal_name ?: $school->trading_name }}</div>
</body></html>
