<script setup lang="ts">
import { Button } from '@/components/ui/button';
import { Bell, Building2, X } from 'lucide-vue-next';
defineProps<{ open: boolean; announcement: any | null; preview?: boolean }>();
defineEmits<{ close: [] }>();
const date=(value?:string)=>value?new Date(value).toLocaleString('fr-FR',{dateStyle:'long',timeStyle:'short'}):'Aperçu avant publication';
</script>
<template><Teleport to="body"><div v-if="open&&announcement" class="fixed inset-0 z-[100] flex bg-slate-950/70 p-0 backdrop-blur-sm sm:p-5" role="dialog" aria-modal="true"><div class="relative m-auto flex max-h-full w-full max-w-5xl flex-col overflow-hidden bg-white shadow-2xl sm:rounded-3xl">
<header class="flex shrink-0 items-center justify-between border-b px-5 py-4 sm:px-7"><div class="flex min-w-0 items-center gap-3"><span class="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Building2 class="size-5"/></span><div class="min-w-0"><p class="text-xs font-semibold uppercase tracking-widest text-primary">{{preview?'Aperçu administrateur':'Communication de l’école'}}</p><p class="truncate text-sm text-slate-500">{{date(announcement.published_at)}}</p></div></div><Button size="icon" variant="ghost" aria-label="Fermer" @click="$emit('close')"><X class="size-5"/></Button></header>
<div class="min-h-0 flex-1 overflow-y-auto"><div v-if="announcement.poster_url" class="bg-slate-100"><img :src="announcement.poster_url" :alt="announcement.title" class="mx-auto max-h-[58vh] w-full object-contain"/></div><div v-else class="grid min-h-72 place-items-center bg-gradient-to-br from-primary via-teal-500 to-cyan-700 px-8 py-16 text-center text-white"><div><Bell class="mx-auto mb-5 size-10 opacity-80"/><h1 class="max-w-3xl text-4xl font-black leading-tight sm:text-6xl">{{announcement.title}}</h1></div></div><article class="mx-auto max-w-4xl px-6 py-8 sm:px-10 sm:py-10"><h1 v-if="announcement.poster_url" class="text-3xl font-bold leading-tight text-slate-900 sm:text-4xl">{{announcement.title}}</h1><div class="mt-5 whitespace-pre-wrap text-base leading-8 text-slate-700 sm:text-lg">{{announcement.message}}</div></article></div>
<footer class="flex shrink-0 items-center justify-between border-t bg-slate-50 px-5 py-3 text-xs text-slate-500 sm:px-7"><span>Easy School · Annonce officielle</span><Button size="sm" @click="$emit('close')">J’ai compris</Button></footer></div></div></Teleport></template>
