<?php

use App\Http\Controllers\AccountStatusController;
use App\Http\Controllers\Admin\AcademicYearsController;
use App\Http\Controllers\Admin\AnnouncementsController;
use App\Http\Controllers\Admin\AnnualLeavesController;
use App\Http\Controllers\Admin\AttendanceController;
use App\Http\Controllers\Admin\AuditController;
use App\Http\Controllers\Admin\BadgesController;
use App\Http\Controllers\Admin\CertificatesController;
use App\Http\Controllers\Admin\ClassroomsController;
use App\Http\Controllers\Admin\CompanySettingsController;
use App\Http\Controllers\Admin\CoursesController;
use App\Http\Controllers\Admin\EmployeeHrRecordsController;
use App\Http\Controllers\Admin\EmployeeTypesController;
use App\Http\Controllers\Admin\EnrollmentFormsController;
use App\Http\Controllers\Admin\ExpensesController;
use App\Http\Controllers\Admin\GroupsController;
use App\Http\Controllers\Admin\ParentsController;
use App\Http\Controllers\Admin\PortalAccountsController;
use App\Http\Controllers\Admin\PrivateSchoolCampaignsController;
use App\Http\Controllers\Admin\PrivateSchoolInscriptionsController;
use App\Http\Controllers\Admin\ReportsController;
use App\Http\Controllers\Admin\SalariesController;
use App\Http\Controllers\Admin\SchoolAttendanceController;
use App\Http\Controllers\Admin\SchoolAttendanceReportController;
use App\Http\Controllers\Admin\SchoolDocumentsController;
use App\Http\Controllers\Admin\SchoolSitesController;
use App\Http\Controllers\Admin\SickLeavesController;
use App\Http\Controllers\Admin\StaffController;
use App\Http\Controllers\Admin\StudentFinanceController;
use App\Http\Controllers\Admin\StudentsController;
use App\Http\Controllers\Admin\SubjectsController;
use App\Http\Controllers\Admin\TimetableController;
use App\Http\Controllers\Admin\TrainingPlansController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Api\AcademicPeriodController as TimetableAcademicPeriodController;
use App\Http\Controllers\Api\TeacherAvailabilityController as TimetableTeacherAvailabilityController;
use App\Http\Controllers\Api\TimetableCatalogueController;
use App\Http\Controllers\Api\TimetableSessionController;
use App\Http\Controllers\Api\TimetableSettingController;
use App\Http\Controllers\Auth\TenantRegistrationController;
use App\Http\Controllers\BadgePortalController;
use App\Http\Controllers\CertificateVerificationController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DemoRequestController;
use App\Http\Controllers\FcmTokenController;
use App\Http\Controllers\PortalController;
use App\Http\Controllers\PricingController;
use App\Http\Controllers\PublicEnrollmentController;
use App\Http\Controllers\PublicPrivateSchoolInscriptionController;
use App\Http\Controllers\SalaryPortalController;
use App\Http\Controllers\SuperAdmin\AuthController as SuperAdminAuthController;
use App\Http\Controllers\SuperAdmin\ContactRequestsController as SuperAdminContactRequestsController;
use App\Http\Controllers\SuperAdmin\DashboardController as SuperAdminDashboardController;
use App\Http\Controllers\SuperAdmin\DemoRequestsController as SuperAdminDemoRequestsController;
use App\Http\Controllers\SuperAdmin\RegistrationRequestsController as SuperAdminRegistrationRequestsController;
use App\Http\Controllers\SuperAdmin\SubscriptionPlansController as SuperAdminSubscriptionPlansController;
use App\Http\Controllers\SuperAdmin\TenantsController as SuperAdminTenantsController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/', fn () => Inertia::render('Welcome'))->middleware('website-available')->name('home');
Route::get('/demo', [DemoRequestController::class, 'create'])->middleware('website-available')->name('demo.create');
Route::post('/demo', [DemoRequestController::class, 'store'])->middleware(['website-available', 'throttle:5,1'])->name('demo.store');
Route::get('/demo/requested', [DemoRequestController::class, 'requested'])->middleware('website-available')->name('demo.requested');
Route::get('/pricing', PricingController::class)->middleware('website-available')->name('pricing');
Route::get('/contact', [ContactController::class, 'create'])->middleware('website-available')->name('contact.create');
Route::post('/contact', [ContactController::class, 'store'])->middleware(['website-available', 'throttle:5,1'])->name('contact.store');

Route::middleware('guest')->group(function () {
    Route::get('/register-school', [TenantRegistrationController::class, 'create'])->name('tenant.register');
    Route::post('/register-school', [TenantRegistrationController::class, 'store'])->middleware('throttle:5,1')->name('tenant.register.store');
});

$superAdminPath = trim((string) config('saas.super_admin_path'), '/');
if ($superAdminPath !== '') {
    Route::get("/{$superAdminPath}/login", [SuperAdminAuthController::class, 'create'])->name('super-admin.login');
    Route::post("/{$superAdminPath}/login", [SuperAdminAuthController::class, 'store'])->middleware('throttle:5,1')->name('super-admin.authenticate');

    Route::middleware('super-admin')->prefix($superAdminPath)->as('super-admin.')->group(function () {
        Route::get('dashboard', SuperAdminDashboardController::class)->name('dashboard');
        Route::post('logout', [SuperAdminAuthController::class, 'destroy'])->name('logout');
        Route::get('schools', [SuperAdminTenantsController::class, 'index'])->name('tenants.index');
        Route::post('schools', [SuperAdminTenantsController::class, 'store'])->name('tenants.store');
        Route::get('schools/{tenant}', [SuperAdminTenantsController::class, 'show'])->name('tenants.show');
        Route::post('schools/{tenant}', [SuperAdminTenantsController::class, 'update'])->name('tenants.update');
        Route::patch('schools/{tenant}/status', [SuperAdminTenantsController::class, 'status'])->name('tenants.status');
        Route::post('schools/{tenant}/subscription', [SuperAdminTenantsController::class, 'subscription'])->name('tenants.subscription');
        Route::get('schools/{tenant}/payments/{payment}/proof', [SuperAdminTenantsController::class, 'paymentProof'])->name('tenants.payments.proof');
        Route::put('schools/{tenant}/administrator', [SuperAdminTenantsController::class, 'administrator'])->name('tenants.administrator');
        Route::delete('schools/{tenant}', [SuperAdminTenantsController::class, 'destroy'])->name('tenants.destroy');
        Route::get('plans', [SuperAdminSubscriptionPlansController::class, 'index'])->name('plans.index');
        Route::post('plans', [SuperAdminSubscriptionPlansController::class, 'store'])->name('plans.store');
        Route::put('plans/{plan}', [SuperAdminSubscriptionPlansController::class, 'update'])->name('plans.update');
        Route::delete('plans/{plan}', [SuperAdminSubscriptionPlansController::class, 'destroy'])->name('plans.destroy');
        Route::put('plans/assign/school', [SuperAdminSubscriptionPlansController::class, 'assign'])->name('plans.assign');
        Route::get('demo-requests', [SuperAdminDemoRequestsController::class, 'index'])->name('demo-requests.index');
        Route::post('demo-requests', [SuperAdminDemoRequestsController::class, 'store'])->name('demo-requests.store');
        Route::post('demo-requests/{demoRequest}/approve', [SuperAdminDemoRequestsController::class, 'approve'])->name('demo-requests.approve');
        Route::post('demo-requests/{demoRequest}/reject', [SuperAdminDemoRequestsController::class, 'reject'])->name('demo-requests.reject');
        Route::patch('demo-requests/{demoRequest}/extend', [SuperAdminDemoRequestsController::class, 'extend'])->name('demo-requests.extend');
        Route::patch('demo-requests/{demoRequest}/suspend', [SuperAdminDemoRequestsController::class, 'suspend'])->name('demo-requests.suspend');
        Route::get('registrations', [SuperAdminRegistrationRequestsController::class, 'index'])->name('registrations.index');
        Route::post('registrations/{tenant}/approve', [SuperAdminRegistrationRequestsController::class, 'approve'])->name('registrations.approve');
        Route::post('registrations/{tenant}/reject', [SuperAdminRegistrationRequestsController::class, 'reject'])->name('registrations.reject');
        Route::get('registrations/{tenant}/payment-proof', [SuperAdminRegistrationRequestsController::class, 'proof'])->name('registrations.proof');
        Route::get('contact-requests', [SuperAdminContactRequestsController::class, 'index'])->name('contact-requests.index');
        Route::patch('contact-requests/{contactRequest}', [SuperAdminContactRequestsController::class, 'update'])->name('contact-requests.update');
    });
}

Route::get('inscription/confirmer/{enrollment}/{token}', [PublicEnrollmentController::class, 'confirm'])->middleware('signed')->name('public.enrollment.confirm');
Route::get('inscription/{enrollmentForm:public_token}', [PublicEnrollmentController::class, 'show'])->name('public.enrollment.show');
Route::post('inscription/{enrollmentForm:public_token}', [PublicEnrollmentController::class, 'store'])->middleware('throttle:10,1')->name('public.enrollment.store');
Route::get('ecole/inscription/{campaign:public_token}', [PublicPrivateSchoolInscriptionController::class, 'show'])->name('public.private-school-inscription.show');
Route::post('ecole/inscription/{campaign:public_token}', [PublicPrivateSchoolInscriptionController::class, 'store'])->middleware('throttle:10,1')->name('public.private-school-inscription.store');
Route::get('carte/verifier/{token}', [BadgePortalController::class, 'verify'])->name('badges.verify');
Route::get('carte/qr/{token}', [BadgePortalController::class, 'qr'])->name('badges.qr');
Route::get('carte/barcode/{token}', [BadgePortalController::class, 'barcode'])->name('badges.barcode');
Route::get('certificats/verifier/{token}', CertificateVerificationController::class)->name('certificates.verify');
Route::get('/firebase/config', [FcmTokenController::class, 'configuration'])->name('firebase.configuration');
Route::get('/firebase-messaging-sw.js', [FcmTokenController::class, 'serviceWorker'])->name('firebase.service-worker');

Route::middleware(['auth', 'verified', 'active'])->get('/dashboard', DashboardController::class)->name('dashboard');
Route::middleware(['auth', 'verified', 'active', 'admin', 'private-school'])
    ->get('/school-inscription', [PrivateSchoolInscriptionsController::class, 'index'])
    ->name('school-inscription');
Route::middleware('auth')->get('/account/pending', AccountStatusController::class)->name('account.pending');
Route::middleware(['auth', 'verified', 'active'])->get('/my/salary', SalaryPortalController::class)->name('salary.mine');
Route::middleware(['auth', 'verified', 'active'])->get('/my/salary/statements/{statement}/download', [SalaryPortalController::class, 'statement'])->name('salary.mine.statement');
Route::middleware(['auth', 'verified', 'active'])->get('/my/salary/payments/{payment}/receipt', [SalaryPortalController::class, 'receipt'])->name('salary.mine.receipt');
Route::middleware(['auth', 'verified', 'active'])->get('/my/card', [BadgePortalController::class, 'mine'])->name('badges.mine');
Route::middleware(['auth', 'verified', 'active'])->group(function () {
    Route::post('/fcm/tokens', [FcmTokenController::class, 'store'])->name('fcm.tokens.store');
    Route::delete('/fcm/tokens', [FcmTokenController::class, 'destroy'])->name('fcm.tokens.destroy');
    Route::get('/portal', [PortalController::class, 'dashboard'])->name('portal.dashboard');
    Route::get('/portal/students/{student}', [PortalController::class, 'studentFolder'])->name('portal.students.show');
    Route::get('/portal/children/{student}', [PortalController::class, 'childFolder'])->name('portal.children.show');
    Route::post('/portal/students/{student}/observations', [PortalController::class, 'storeObservation'])->name('portal.students.observations.store');
    Route::get('/portal/{section}', [PortalController::class, 'section'])->name('portal.section');
    Route::put('/portal/sessions/{session}/attendance', [PortalController::class, 'attendance'])->name('portal.attendance');
    Route::patch('/portal/notifications/{notification}/read', [PortalController::class, 'read'])->name('portal.notifications.read');
    Route::patch('/portal/notifications/read-all', [PortalController::class, 'readAll'])->name('portal.notifications.read-all');
    Route::get('/portal/payments/{payment}/receipt', [PortalController::class, 'receipt'])->name('portal.payments.receipt');
});

Route::middleware(['auth', 'verified', 'active', 'admin'])
    ->prefix('admin')
    ->as('admin.')
    ->group(function () {
        Route::middleware('private-school')->group(function () {
            Route::get('academic-years', [AcademicYearsController::class, 'index'])->name('academic-years.index');
            Route::post('academic-years', [AcademicYearsController::class, 'store'])->name('academic-years.store');
            Route::put('academic-years/{academicYear}', [AcademicYearsController::class, 'update'])->name('academic-years.update');
            Route::patch('academic-years/{academicYear}/activate', [AcademicYearsController::class, 'activate'])->name('academic-years.activate');
            Route::patch('academic-years/{academicYear}/close', [AcademicYearsController::class, 'close'])->name('academic-years.close');
            Route::patch('academic-years/{academicYear}/archive', [AcademicYearsController::class, 'archive'])->name('academic-years.archive');
            Route::post('academic-years/select', [AcademicYearsController::class, 'select'])->name('academic-years.select');
            Route::post('academic-years/{academicYear}/calendar-events', [AcademicYearsController::class, 'storeCalendarEvent'])->name('academic-years.calendar-events.store');
            Route::put('academic-years/{academicYear}/calendar-events/{calendarEvent}', [AcademicYearsController::class, 'updateCalendarEvent'])->name('academic-years.calendar-events.update');
            Route::delete('academic-years/{academicYear}/calendar-events/{calendarEvent}', [AcademicYearsController::class, 'destroyCalendarEvent'])->name('academic-years.calendar-events.destroy');
            Route::get('inscription-campaigns', [PrivateSchoolCampaignsController::class, 'index'])->name('private-school-campaigns.index');
            Route::post('inscription-campaigns', [PrivateSchoolCampaignsController::class, 'store'])->name('private-school-campaigns.store');
            Route::put('inscription-campaigns/{campaign}', [PrivateSchoolCampaignsController::class, 'update'])->name('private-school-campaigns.update');
            Route::patch('inscription-campaigns/{campaign}/status', [PrivateSchoolCampaignsController::class, 'status'])->name('private-school-campaigns.status');
            Route::get('school-inscriptions', [PrivateSchoolInscriptionsController::class, 'index'])->name('private-school-inscriptions.index');
            Route::patch('school-inscriptions/{inscription}/status', [PrivateSchoolInscriptionsController::class, 'updateStatus'])->name('private-school-inscriptions.status');
            Route::get('school-attendance', [SchoolAttendanceController::class, 'index'])->name('school-attendance.index');
            Route::post('school-attendance/exceptions', [SchoolAttendanceController::class, 'store'])->name('school-attendance.store');
            Route::post('school-attendance/students/bulk', [SchoolAttendanceController::class, 'bulkStudents'])->name('school-attendance.students.bulk');
            Route::delete('school-attendance/exceptions/{attendanceException}', [SchoolAttendanceController::class, 'destroy'])->name('school-attendance.destroy');
            Route::get('school-attendance/teacher-preview', [SchoolAttendanceController::class, 'teacherPreview'])->name('school-attendance.teacher-preview');
            Route::get('school-attendance/reports', [SchoolAttendanceReportController::class, 'index'])->name('school-attendance.reports');
            Route::get('school-attendance/reports/export/{format}', [SchoolAttendanceReportController::class, 'export'])->whereIn('format', ['csv', 'pdf'])->name('school-attendance.reports.export');
            Route::put('school-attendance/settings', [SchoolAttendanceReportController::class, 'updateSettings'])->name('school-attendance.settings.update');
            Route::get('school-documents', [SchoolDocumentsController::class, 'index'])->name('school-documents.index');
            Route::post('school-documents/download', [SchoolDocumentsController::class, 'download'])->name('school-documents.download');
        });
        Route::get('timetable', TimetableController::class)->name('timetable.index');
        Route::prefix('timetable-api')->as('timetable-api.')->group(function () {
            Route::get('catalogue', TimetableCatalogueController::class)->name('catalogue');
            Route::get('settings', [TimetableSettingController::class, 'show'])->name('settings.show');
            Route::put('settings', [TimetableSettingController::class, 'update'])->name('settings.update');
            Route::put('groups/{group}/defaults', [TimetableSettingController::class, 'updateGroupDefaults'])->name('groups.defaults.update');
            Route::get('teachers/{teacher}/availability', [TimetableTeacherAvailabilityController::class, 'index'])->name('teachers.availability.index');
            Route::post('teachers/{teacher}/availability', [TimetableTeacherAvailabilityController::class, 'storeWeekly'])->name('teachers.availability.store');
            Route::post('teachers/{teacher}/unavailable-periods', [TimetableTeacherAvailabilityController::class, 'storeUnavailable'])->name('teachers.unavailable-periods.store');
            Route::delete('teacher-availabilities/{availability}', [TimetableTeacherAvailabilityController::class, 'destroyWeekly'])->name('teacher-availabilities.destroy');
            Route::delete('teacher-unavailable-periods/{unavailablePeriod}', [TimetableTeacherAvailabilityController::class, 'destroyUnavailable'])->name('teacher-unavailable-periods.destroy');
            Route::post('sessions/check-conflicts', [TimetableSessionController::class, 'check'])->name('sessions.check');
            Route::get('calendar', [TimetableSessionController::class, 'calendar'])->name('calendar');
            Route::post('sessions/{timetableSession}/duplicate', [TimetableSessionController::class, 'duplicate'])->name('sessions.duplicate');
            Route::patch('sessions/{timetableSession}/move', [TimetableSessionController::class, 'move'])->name('sessions.move');
            Route::patch('sessions/{timetableSession}/replace-teacher', [TimetableSessionController::class, 'replaceTeacher'])->name('sessions.replace-teacher');
            Route::patch('sessions/{timetableSession}/change-room', [TimetableSessionController::class, 'changeRoom'])->name('sessions.change-room');
            Route::patch('sessions/{timetableSession}/cancel', [TimetableSessionController::class, 'cancel'])->name('sessions.cancel');
            Route::apiResource('academic-periods', TimetableAcademicPeriodController::class)->parameters(['academic-periods' => 'academicPeriod']);
            Route::apiResource('sessions', TimetableSessionController::class)->parameters(['sessions' => 'timetableSession']);
        });
        Route::get('groups', [GroupsController::class, 'index'])->name('groups.index');
        Route::post('groups', [GroupsController::class, 'store'])->name('groups.store');
        Route::get('groups/{group}', [GroupsController::class, 'show'])->name('groups.show');
        Route::put('groups/{group}', [GroupsController::class, 'update'])->name('groups.update');
        Route::delete('groups/{group}', [GroupsController::class, 'destroy'])->name('groups.destroy');
        Route::post('groups/{group}/students', [GroupsController::class, 'assignStudents'])->name('groups.students.assign');
        Route::delete('groups/{group}/students/{student}', [GroupsController::class, 'removeStudent'])->name('groups.students.remove');
        Route::post('school-levels', [GroupsController::class, 'storeLevel'])->name('school-levels.store');
        Route::put('school-levels/{level}', [GroupsController::class, 'updateLevel'])->name('school-levels.update');
        Route::delete('school-levels/{level}', [GroupsController::class, 'destroyLevel'])->name('school-levels.destroy');
        Route::get('subjects', [SubjectsController::class, 'index'])->name('subjects.index');
        Route::post('subjects', [SubjectsController::class, 'store'])->name('subjects.store');
        Route::post('subjects/load-default-curriculum', [SubjectsController::class, 'loadDefaultCurriculum'])->name('subjects.curriculum.load');
        Route::put('subjects/{subject}', [SubjectsController::class, 'update'])->name('subjects.update');
        Route::delete('subjects/{subject}', [SubjectsController::class, 'destroy'])->name('subjects.destroy');
        Route::patch('subjects/{subject}/toggle', [SubjectsController::class, 'toggle'])->name('subjects.toggle');
        Route::get('attendance', [AttendanceController::class, 'index'])->name('attendance.index');
        Route::put('attendance/sessions/{session}/students', [AttendanceController::class, 'students'])->name('attendance.students');
        Route::patch('attendance/sessions/{session}/validate', [AttendanceController::class, 'validateSheet'])->name('attendance.validate');
        Route::put('attendance/sessions/{session}/teacher', [AttendanceController::class, 'teacher'])->name('attendance.teacher');
        Route::put('attendance/teachers/bulk', [AttendanceController::class, 'teachersBulk'])->name('attendance.teachers.bulk');
        Route::put('attendance/employees', [AttendanceController::class, 'employee'])->name('attendance.employee');
        Route::get('staff/types', [StaffController::class, 'types'])->name('staff.types');
        Route::post('staff/types', [EmployeeTypesController::class, 'store'])->name('staff.types.store');
        Route::put('staff/types/{employeeType}', [EmployeeTypesController::class, 'update'])->name('staff.types.update');
        Route::get('staff', [StaffController::class, 'index'])->name('staff.index');
        Route::post('staff', [StaffController::class, 'store'])->name('staff.store');
        Route::get('staff/{staff}/edit', [StaffController::class, 'edit'])->name('staff.edit');
        Route::post('staff/{staff}/documents', [StaffController::class, 'storeDocuments'])->name('staff.documents.store');
        Route::delete('staff/{staff}/documents/{document}', [StaffController::class, 'destroyDocument'])->name('staff.documents.destroy');
        Route::post('staff/{staff}/annual-leaves', [AnnualLeavesController::class, 'store'])->name('staff.annual-leaves.store');
        Route::patch('staff/{staff}/annual-leaves/{annualLeave}/approve', [AnnualLeavesController::class, 'approve'])->name('staff.annual-leaves.approve');
        Route::patch('staff/{staff}/annual-leaves/{annualLeave}/reject', [AnnualLeavesController::class, 'reject'])->name('staff.annual-leaves.reject');
        Route::patch('staff/{staff}/annual-leaves/{annualLeave}/cancel', [AnnualLeavesController::class, 'cancel'])->name('staff.annual-leaves.cancel');
        Route::patch('staff/{staff}/annual-leaves/{annualLeave}/complete', [AnnualLeavesController::class, 'complete'])->name('staff.annual-leaves.complete');
        Route::get('staff/{staff}/annual-leaves/{annualLeave}/print', [AnnualLeavesController::class, 'print'])->name('staff.annual-leaves.print');
        Route::post('staff/{staff}/sick-leaves', [SickLeavesController::class, 'store'])->name('staff.sick-leaves.store');
        Route::patch('staff/{staff}/sick-leaves/{sickLeave}/approve', [SickLeavesController::class, 'approve'])->name('staff.sick-leaves.approve');
        Route::patch('staff/{staff}/sick-leaves/{sickLeave}/reject', [SickLeavesController::class, 'reject'])->name('staff.sick-leaves.reject');
        Route::patch('staff/{staff}/sick-leaves/{sickLeave}/cancel', [SickLeavesController::class, 'cancel'])->name('staff.sick-leaves.cancel');
        Route::patch('staff/{staff}/sick-leaves/{sickLeave}/complete', [SickLeavesController::class, 'complete'])->name('staff.sick-leaves.complete');
        Route::get('staff/{staff}/sick-leaves/{sickLeave}/print', [SickLeavesController::class, 'print'])->name('staff.sick-leaves.print');
        Route::post('staff/{staff}/hr-records', [EmployeeHrRecordsController::class, 'store'])->name('staff.hr-records.store');
        Route::patch('staff/{staff}/hr-records/{hrRecord}/status', [EmployeeHrRecordsController::class, 'updateStatus'])->name('staff.hr-records.status');
        Route::patch('staff/{staff}/hr-records/{hrRecord}/archive', [EmployeeHrRecordsController::class, 'archive'])->name('staff.hr-records.archive');
        Route::get('staff/{staff}', [StaffController::class, 'show'])->name('staff.show');
        Route::post('staff/{staff}', [StaffController::class, 'update'])->name('staff.update');
        Route::patch('staff/{staff}/toggle-active', [StaffController::class, 'toggleActive'])->name('staff.toggle-active');
        Route::get('settings', [CompanySettingsController::class, 'edit'])->name('settings.edit');
        Route::put('settings', [CompanySettingsController::class, 'update'])->name('settings.update');
        Route::get('users', [UsersController::class, 'index'])->name('users.index');
        Route::post('users', [UsersController::class, 'store'])->name('users.store');
        Route::put('users/{user}', [UsersController::class, 'update'])->name('users.update');
        Route::patch('users/{user}/toggle-active', [UsersController::class, 'toggleActive'])->name('users.toggle-active');
        Route::get('classrooms', [ClassroomsController::class, 'index'])->name('classrooms.index');
        Route::post('classrooms', [ClassroomsController::class, 'store'])->name('classrooms.store');
        Route::put('classrooms/{classroom}', [ClassroomsController::class, 'update'])->name('classrooms.update');
        Route::patch('classrooms/{classroom}/toggle-active', [ClassroomsController::class, 'toggleActive'])->name('classrooms.toggle-active');
        Route::get('sites', [SchoolSitesController::class, 'index'])->name('sites.index');
        Route::post('sites', [SchoolSitesController::class, 'store'])->name('sites.store');
        Route::put('sites/{site}', [SchoolSitesController::class, 'update'])->name('sites.update');
        Route::patch('sites/{site}/toggle-active', [SchoolSitesController::class, 'toggleActive'])->name('sites.toggle-active');
        Route::get('courses', [CoursesController::class, 'index'])->name('courses.index');
        Route::post('courses', [CoursesController::class, 'store'])->name('courses.store');
        Route::put('courses/{course}', [CoursesController::class, 'update'])->name('courses.update');
        Route::patch('courses/{course}/toggle-active', [CoursesController::class, 'toggleActive'])->name('courses.toggle-active');
        Route::post('courses/{course}/levels', [CoursesController::class, 'storeLevel'])->name('courses.levels.store');
        Route::put('courses/{course}/levels/{level}', [CoursesController::class, 'updateLevel'])->name('courses.levels.update');
        Route::patch('courses/{course}/levels/{level}/toggle-active', [CoursesController::class, 'toggleLevel'])->name('courses.levels.toggle-active');
        Route::get('students', [StudentsController::class, 'index'])->name('students.index');
        Route::get('parents', [ParentsController::class, 'index'])->name('parents.index');
        Route::post('parents', [ParentsController::class, 'store'])->name('parents.store');
        Route::get('parents/lookup', [ParentsController::class, 'lookup'])->name('parents.lookup');
        Route::put('parents/{parent}', [ParentsController::class, 'update'])->name('parents.update');
        Route::patch('parents/{parent}/toggle', [ParentsController::class, 'toggle'])->name('parents.toggle');
        Route::patch('parents/{parent}/children/{student}/visibility', [ParentsController::class, 'toggleChildVisibility'])->name('parents.children.visibility');
        Route::post('students', [StudentsController::class, 'store'])->name('students.store');
        Route::get('students/{student}', [StudentsController::class, 'show'])->name('students.show');
        Route::put('students/{student}', [StudentsController::class, 'update'])->name('students.update');
        Route::patch('students/{student}/status', [StudentsController::class, 'updateStatus'])->name('students.status');
        Route::put('students/{student}/documents', [StudentsController::class, 'updateDocuments'])->name('students.documents');
        Route::patch('students/{student}/toggle-active', [StudentsController::class, 'toggleActive'])->name('students.toggle-active');
        Route::post('students/{student}/portal-account', [PortalAccountsController::class, 'student'])->name('students.portal-account');
        Route::post('notifications/announcements', [AnnouncementsController::class, 'store'])->name('notifications.announcements.store');
        Route::get('certificates', [CertificatesController::class, 'index'])->name('certificates.index');
        Route::post('certificates', [CertificatesController::class, 'store'])->name('certificates.store');
        Route::post('certificates/bulk', [CertificatesController::class, 'storeBulk'])->name('certificates.bulk.store');
        Route::get('certificates/{certificate}/print', [CertificatesController::class, 'print'])->name('certificates.print');
        Route::get('reports', [ReportsController::class, 'index'])->name('reports.index');
        Route::get('reports/export/{format}', [ReportsController::class, 'export'])->whereIn('format', ['csv', 'pdf'])->name('reports.export');
        Route::get('audit', AuditController::class)->name('audit.index');
        Route::get('finance', [StudentFinanceController::class, 'index'])->name('finance.index');
        Route::get('finance/settings', [StudentFinanceController::class, 'settings'])->name('finance.settings');
        Route::get('badges', [BadgesController::class, 'index'])->name('badges.index');
        Route::post('badges', [BadgesController::class, 'store'])->name('badges.store');
        Route::patch('badges/{badge}/status', [BadgesController::class, 'status'])->name('badges.status');
        Route::post('badges/{badge}/reissue', [BadgesController::class, 'reissue'])->name('badges.reissue');
        Route::get('badges/{badge}/print', [BadgesController::class, 'print'])->name('badges.print');
        Route::post('badges/print-batch', [BadgesController::class, 'batch'])->name('badges.print-batch');
        Route::put('finance/enrollments/{enrollment}', [StudentFinanceController::class, 'configure'])->name('finance.enrollments.configure');
        Route::post('finance/enrollments/{enrollment}/adjustments', [StudentFinanceController::class, 'adjustment'])->name('finance.adjustments.store');
        Route::post('finance/enrollments/{enrollment}/payments', [StudentFinanceController::class, 'pay'])->name('finance.payments.store');
        Route::post('finance/payments/{payment}/reverse', [StudentFinanceController::class, 'reverse'])->name('finance.payments.reverse');
        Route::get('finance/payments/{payment}/receipt', [StudentFinanceController::class, 'receipt'])->name('finance.payments.receipt');
        Route::get('enrollment-forms', [EnrollmentFormsController::class, 'index'])->name('enrollment-forms.index');
        Route::get('enrollment-forms/{enrollmentForm}', [EnrollmentFormsController::class, 'show'])->name('enrollment-forms.show');
        Route::post('enrollment-forms', [EnrollmentFormsController::class, 'store'])->name('enrollment-forms.store');
        Route::put('enrollment-forms/{enrollmentForm}', [EnrollmentFormsController::class, 'update'])->name('enrollment-forms.update');
        Route::patch('enrollment-forms/{enrollmentForm}/toggle-active', [EnrollmentFormsController::class, 'toggleActive'])->name('enrollment-forms.toggle-active');
        Route::patch('enrollment-forms/{enrollmentForm}/enrollments/{enrollment}/group', [EnrollmentFormsController::class, 'updateGroup'])->name('enrollment-forms.enrollments.group');
        Route::patch('enrollment-forms/{enrollmentForm}/enrollments/{enrollment}/status', [EnrollmentFormsController::class, 'updateEnrollmentStatus'])->name('enrollment-forms.enrollments.status');
        Route::post('enrollment-forms/{enrollmentForm}/enrollments/{enrollment}/register', [EnrollmentFormsController::class, 'registerApplicant'])->name('enrollment-forms.enrollments.register');
        Route::post('enrollment-forms/{enrollmentForm}/enrollments', [EnrollmentFormsController::class, 'addEnrollment'])->name('enrollment-forms.enrollments.store');
        Route::delete('enrollment-forms/{enrollmentForm}/enrollments/{enrollment}', [EnrollmentFormsController::class, 'removeEnrollment'])->name('enrollment-forms.enrollments.destroy');
        Route::get('expenses', [ExpensesController::class, 'index'])->name('expenses.index');
        Route::post('expenses', [ExpensesController::class, 'store'])->name('expenses.store');
        Route::put('expenses/{expense}', [ExpensesController::class, 'update'])->name('expenses.update');
        Route::delete('expenses/{expense}', [ExpensesController::class, 'destroy'])->name('expenses.destroy');
        Route::get('salaries', [SalariesController::class, 'index'])->name('salaries.index');
        Route::get('salaries/declarations', [\App\Http\Controllers\Admin\PayrollDeclarationsController::class, 'index'])->name('salaries.declarations.index');
        Route::post('salaries/declarations', [\App\Http\Controllers\Admin\PayrollDeclarationsController::class, 'store'])->name('salaries.declarations.store');
        Route::patch('salaries/declarations/{declaration}/declared', [\App\Http\Controllers\Admin\PayrollDeclarationsController::class, 'declared'])->name('salaries.declarations.declared');
        Route::post('salaries', [SalariesController::class, 'storeLegacy'])->name('salaries.store');
        Route::get('salaries/configurations', [SalariesController::class, 'configurations'])->name('salaries.configurations.index');
        Route::post('salaries/items', [SalariesController::class, 'storeItem'])->name('salaries.items.store');
        Route::put('salaries/items/{item}', [SalariesController::class, 'updateItem'])->name('salaries.items.update');
        Route::delete('salaries/items/{item}', [SalariesController::class, 'destroyItem'])->name('salaries.items.destroy');
        Route::post('salaries/configurations', [SalariesController::class, 'storeConfiguration'])->name('salaries.configurations.store');
        Route::put('salaries/configurations/{configuration}', [SalariesController::class, 'updateConfiguration'])->name('salaries.configurations.update');
        Route::delete('salaries/configurations/{configuration}', [SalariesController::class, 'destroyConfiguration'])->name('salaries.configurations.destroy');
        Route::get('salaries/attendance-preview', [SalariesController::class, 'attendancePreview'])->name('salaries.attendance-preview');
        Route::post('salaries/generate', [SalariesController::class, 'generate'])->name('salaries.generate');
        Route::post('salaries/{statement}/payments', [SalariesController::class, 'pay'])->name('salaries.payments.store');
        Route::get('salaries/payments/{payment}/receipt', [SalariesController::class, 'paymentReceipt'])->name('salaries.payments.receipt');
        Route::delete('salaries/{statement}', [SalariesController::class, 'destroy'])->name('salaries.destroy');
        Route::get('salaries/{statement}/print', [SalariesController::class, 'print'])->name('salaries.print');
        Route::get('planifications', [TrainingPlansController::class, 'index'])->name('training-plans.index');
        Route::post('planifications', [TrainingPlansController::class, 'store'])->name('training-plans.store');
        Route::get('planifications/{trainingPlan}/parametres', [TrainingPlansController::class, 'settings'])->name('training-plans.settings');
        Route::put('planifications/{trainingPlan}/parametres/principal', [TrainingPlansController::class, 'updateMainAccess'])->name('training-plans.settings.main');
        Route::post('planifications/{trainingPlan}/parametres/enseignants', [TrainingPlansController::class, 'storeTeacherAccess'])->name('training-plans.settings.teachers.store');
        Route::put('planifications/{trainingPlan}/parametres/enseignants/{access}', [TrainingPlansController::class, 'updateTeacherAccess'])->name('training-plans.settings.teachers.update');
        Route::delete('planifications/{trainingPlan}/parametres/enseignants/{access}', [TrainingPlansController::class, 'destroyTeacherAccess'])->name('training-plans.settings.teachers.destroy');
        Route::get('planifications/{trainingPlan}', [TrainingPlansController::class, 'show'])->name('training-plans.show');
        Route::put('planifications/{trainingPlan}', [TrainingPlansController::class, 'update'])->name('training-plans.update');
        Route::post('planifications/{trainingPlan}/groupes', [TrainingPlansController::class, 'storeGroup'])->name('training-plans.groups.store');
        Route::put('planifications/{trainingPlan}/groupes/{group}', [TrainingPlansController::class, 'updateGroup'])->name('training-plans.groups.update');
        Route::delete('planifications/{trainingPlan}/groupes/{group}', [TrainingPlansController::class, 'destroyGroup'])->name('training-plans.groups.destroy');
        Route::post('planifications/{trainingPlan}/groupes/{group}/etudiants', [TrainingPlansController::class, 'addStudent'])->name('training-plans.groups.students.store');
        Route::put('planifications/{trainingPlan}/groupes/{group}/inscriptions/{enrollment}/etudiant', [TrainingPlansController::class, 'updateStudent'])->name('training-plans.groups.students.update');
        Route::patch('planifications/{trainingPlan}/groupes/{group}/inscriptions/{enrollment}/deplacer', [TrainingPlansController::class, 'moveStudent'])->name('training-plans.groups.students.move');
        Route::post('planifications/{trainingPlan}/groupes/{group}/seances', [TrainingPlansController::class, 'storeSession'])->name('training-plans.sessions.store');
        Route::put('planifications/{trainingPlan}/groupes/{group}/seances/{session}', [TrainingPlansController::class, 'updateSession'])->name('training-plans.sessions.update');
        Route::delete('planifications/{trainingPlan}/groupes/{group}/seances/{session}', [TrainingPlansController::class, 'destroySession'])->name('training-plans.sessions.destroy');
        Route::patch('planifications/{trainingPlan}/groupes/{group}/seances/{session}/complete', [TrainingPlansController::class, 'completeSession'])->name('training-plans.sessions.complete');
        Route::put('planifications/{trainingPlan}/groupes/{group}/seances/{session}/presences', [TrainingPlansController::class, 'recordAttendance'])->name('training-plans.sessions.attendance');
    });
require __DIR__.'/settings.php';
require __DIR__.'/auth.php';
