<?php

use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
use App\Http\Controllers\Admin\CompanySettingsController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\ClassroomsController;
use App\Http\Controllers\Admin\SchoolSitesController;
use App\Http\Controllers\Admin\CoursesController;
use App\Http\Controllers\Admin\StudentsController;
use App\Http\Controllers\Admin\EnrollmentFormsController;
use App\Http\Controllers\Admin\ExpensesController;
use App\Http\Controllers\Admin\SalariesController;
use App\Http\Controllers\PublicEnrollmentController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Admin\TrainingPlansController;
use App\Http\Controllers\Admin\StaffController;
use App\Http\Controllers\Admin\EmployeeTypesController;
use App\Http\Controllers\SalaryPortalController;
use App\Http\Controllers\Admin\StudentFinanceController;
use App\Http\Controllers\Admin\BadgesController;
use App\Http\Controllers\BadgePortalController;
use App\Http\Controllers\PortalController;
use App\Http\Controllers\Admin\PortalAccountsController;
use App\Http\Controllers\Admin\AnnouncementsController;
use App\Http\Controllers\Admin\CertificatesController;
use App\Http\Controllers\CertificateVerificationController;
use App\Http\Controllers\Admin\ReportsController;
use App\Http\Controllers\Admin\AuditController;
use App\Http\Controllers\Admin\AttendanceController;

Route::redirect('/', '/login')->name('home');

Route::get('inscription/confirmer/{enrollment}/{token}', [PublicEnrollmentController::class, 'confirm'])->middleware('signed')->name('public.enrollment.confirm');
Route::get('inscription/{enrollmentForm:public_token}', [PublicEnrollmentController::class, 'show'])->name('public.enrollment.show');
Route::post('inscription/{enrollmentForm:public_token}', [PublicEnrollmentController::class, 'store'])->middleware('throttle:10,1')->name('public.enrollment.store');
Route::get('carte/verifier/{token}', [BadgePortalController::class, 'verify'])->name('badges.verify');
Route::get('carte/qr/{token}', [BadgePortalController::class, 'qr'])->name('badges.qr');
Route::get('carte/barcode/{token}', [BadgePortalController::class, 'barcode'])->name('badges.barcode');
Route::get('certificats/verifier/{token}', CertificateVerificationController::class)->name('certificates.verify');

Route::middleware(['auth', 'verified', 'active'])->get('/dashboard', DashboardController::class)->name('dashboard');
Route::middleware(['auth','verified','active'])->get('/my/salary', SalaryPortalController::class)->name('salary.mine');
Route::middleware(['auth','verified','active'])->get('/my/card', [BadgePortalController::class, 'mine'])->name('badges.mine');
Route::middleware(['auth','verified','active'])->group(function(){
    Route::get('/portal',[PortalController::class,'dashboard'])->name('portal.dashboard');
    Route::get('/portal/{section}',[PortalController::class,'section'])->name('portal.section');
    Route::put('/portal/sessions/{session}/attendance',[PortalController::class,'attendance'])->name('portal.attendance');
    Route::patch('/portal/notifications/{notification}/read',[PortalController::class,'read'])->name('portal.notifications.read');
    Route::patch('/portal/notifications/read-all',[PortalController::class,'readAll'])->name('portal.notifications.read-all');
    Route::get('/portal/payments/{payment}/receipt',[PortalController::class,'receipt'])->name('portal.payments.receipt');
});

Route::middleware(['auth', 'verified', 'active', 'admin'])
    ->prefix('admin')
    ->as('admin.')
    ->group(function () {
        Route::get('attendance',[AttendanceController::class,'index'])->name('attendance.index');
        Route::put('attendance/sessions/{session}/students',[AttendanceController::class,'students'])->name('attendance.students');
        Route::patch('attendance/sessions/{session}/validate',[AttendanceController::class,'validateSheet'])->name('attendance.validate');
        Route::put('attendance/sessions/{session}/teacher',[AttendanceController::class,'teacher'])->name('attendance.teacher');
        Route::put('attendance/teachers/bulk',[AttendanceController::class,'teachersBulk'])->name('attendance.teachers.bulk');
        Route::put('attendance/employees',[AttendanceController::class,'employee'])->name('attendance.employee');
        Route::get('staff/types', [StaffController::class, 'types'])->name('staff.types');
        Route::post('staff/types', [EmployeeTypesController::class, 'store'])->name('staff.types.store');
        Route::put('staff/types/{employeeType}', [EmployeeTypesController::class, 'update'])->name('staff.types.update');
        Route::get('staff', [StaffController::class, 'index'])->name('staff.index');
        Route::post('staff', [StaffController::class, 'store'])->name('staff.store');
        Route::get('staff/{staff}/edit', [StaffController::class, 'edit'])->name('staff.edit');
        Route::get('staff/{staff}', [StaffController::class, 'show'])->name('staff.show');
        Route::post('staff/{staff}', [StaffController::class, 'update'])->name('staff.update');
        Route::patch('staff/{staff}/toggle-active', [StaffController::class, 'toggleActive'])->name('staff.toggle-active');
        Route::get('settings', [CompanySettingsController::class, 'edit'])->name('settings.edit');
        Route::put('settings', [CompanySettingsController::class, 'update'])->name('settings.update');
        Route::get('users', [UsersController::class, 'index'])->name('users.index');
        Route::post('users', [UsersController::class, 'store'])->name('users.store');
        Route::put('users/{user}', [UsersController::class, 'update'])->name('users.update');
        Route::patch('users/{user}/toggle-active', [UsersController::class, 'toggleActive'])->name('users.toggle-active');
        Route::get('classrooms', [ClassroomsController::class, 'index'])->name('classrooms.index');
        Route::post('classrooms', [ClassroomsController::class, 'store'])->name('classrooms.store');
        Route::put('classrooms/{classroom}', [ClassroomsController::class, 'update'])->name('classrooms.update');
        Route::patch('classrooms/{classroom}/toggle-active', [ClassroomsController::class, 'toggleActive'])->name('classrooms.toggle-active');
        Route::get('sites', [SchoolSitesController::class, 'index'])->name('sites.index');
        Route::post('sites', [SchoolSitesController::class, 'store'])->name('sites.store');
        Route::put('sites/{site}', [SchoolSitesController::class, 'update'])->name('sites.update');
        Route::patch('sites/{site}/toggle-active', [SchoolSitesController::class, 'toggleActive'])->name('sites.toggle-active');
        Route::get('courses', [CoursesController::class, 'index'])->name('courses.index');
        Route::post('courses', [CoursesController::class, 'store'])->name('courses.store');
        Route::put('courses/{course}', [CoursesController::class, 'update'])->name('courses.update');
        Route::patch('courses/{course}/toggle-active', [CoursesController::class, 'toggleActive'])->name('courses.toggle-active');
        Route::post('courses/{course}/levels', [CoursesController::class, 'storeLevel'])->name('courses.levels.store');
        Route::put('courses/{course}/levels/{level}', [CoursesController::class, 'updateLevel'])->name('courses.levels.update');
        Route::patch('courses/{course}/levels/{level}/toggle-active', [CoursesController::class, 'toggleLevel'])->name('courses.levels.toggle-active');
        Route::get('students', [StudentsController::class, 'index'])->name('students.index');
        Route::post('students', [StudentsController::class, 'store'])->name('students.store');
        Route::get('students/{student}', [StudentsController::class, 'show'])->name('students.show');
        Route::put('students/{student}', [StudentsController::class, 'update'])->name('students.update');
        Route::patch('students/{student}/status', [StudentsController::class, 'updateStatus'])->name('students.status');
        Route::put('students/{student}/documents', [StudentsController::class, 'updateDocuments'])->name('students.documents');
        Route::patch('students/{student}/toggle-active', [StudentsController::class, 'toggleActive'])->name('students.toggle-active');
        Route::post('students/{student}/portal-account',[PortalAccountsController::class,'student'])->name('students.portal-account');
        Route::post('parents',[PortalAccountsController::class,'parent'])->name('parents.store');
        Route::put('parents/{parent}/children',[PortalAccountsController::class,'children'])->name('parents.children');
        Route::post('notifications/announcements',[AnnouncementsController::class,'store'])->name('notifications.announcements.store');
        Route::get('certificates',[CertificatesController::class,'index'])->name('certificates.index');
        Route::post('certificates',[CertificatesController::class,'store'])->name('certificates.store');
        Route::post('certificates/bulk',[CertificatesController::class,'storeBulk'])->name('certificates.bulk.store');
        Route::get('certificates/{certificate}/print',[CertificatesController::class,'print'])->name('certificates.print');
        Route::get('reports',[ReportsController::class,'index'])->name('reports.index');
        Route::get('reports/export/{format}',[ReportsController::class,'export'])->whereIn('format',['csv','pdf'])->name('reports.export');
        Route::get('audit',AuditController::class)->name('audit.index');
        Route::get('finance', [StudentFinanceController::class, 'index'])->name('finance.index');
        Route::get('finance/settings', [StudentFinanceController::class, 'settings'])->name('finance.settings');
        Route::get('badges', [BadgesController::class, 'index'])->name('badges.index');
        Route::post('badges', [BadgesController::class, 'store'])->name('badges.store');
        Route::patch('badges/{badge}/status', [BadgesController::class, 'status'])->name('badges.status');
        Route::post('badges/{badge}/reissue', [BadgesController::class, 'reissue'])->name('badges.reissue');
        Route::get('badges/{badge}/print', [BadgesController::class, 'print'])->name('badges.print');
        Route::post('badges/print-batch', [BadgesController::class, 'batch'])->name('badges.print-batch');
        Route::put('finance/enrollments/{enrollment}', [StudentFinanceController::class, 'configure'])->name('finance.enrollments.configure');
        Route::post('finance/enrollments/{enrollment}/adjustments', [StudentFinanceController::class, 'adjustment'])->name('finance.adjustments.store');
        Route::post('finance/enrollments/{enrollment}/payments', [StudentFinanceController::class, 'pay'])->name('finance.payments.store');
        Route::post('finance/payments/{payment}/reverse', [StudentFinanceController::class, 'reverse'])->name('finance.payments.reverse');
        Route::get('finance/payments/{payment}/receipt', [StudentFinanceController::class, 'receipt'])->name('finance.payments.receipt');
        Route::get('enrollment-forms', [EnrollmentFormsController::class, 'index'])->name('enrollment-forms.index');
        Route::get('enrollment-forms/{enrollmentForm}', [EnrollmentFormsController::class, 'show'])->name('enrollment-forms.show');
        Route::post('enrollment-forms', [EnrollmentFormsController::class, 'store'])->name('enrollment-forms.store');
        Route::put('enrollment-forms/{enrollmentForm}', [EnrollmentFormsController::class, 'update'])->name('enrollment-forms.update');
        Route::patch('enrollment-forms/{enrollmentForm}/toggle-active', [EnrollmentFormsController::class, 'toggleActive'])->name('enrollment-forms.toggle-active');
        Route::patch('enrollment-forms/{enrollmentForm}/enrollments/{enrollment}/group', [EnrollmentFormsController::class, 'updateGroup'])->name('enrollment-forms.enrollments.group');
        Route::patch('enrollment-forms/{enrollmentForm}/enrollments/{enrollment}/status', [EnrollmentFormsController::class, 'updateEnrollmentStatus'])->name('enrollment-forms.enrollments.status');
        Route::post('enrollment-forms/{enrollmentForm}/enrollments/{enrollment}/register', [EnrollmentFormsController::class, 'registerApplicant'])->name('enrollment-forms.enrollments.register');
        Route::post('enrollment-forms/{enrollmentForm}/enrollments', [EnrollmentFormsController::class, 'addEnrollment'])->name('enrollment-forms.enrollments.store');
        Route::delete('enrollment-forms/{enrollmentForm}/enrollments/{enrollment}', [EnrollmentFormsController::class, 'removeEnrollment'])->name('enrollment-forms.enrollments.destroy');
        Route::get('expenses', [ExpensesController::class, 'index'])->name('expenses.index');
        Route::post('expenses', [ExpensesController::class, 'store'])->name('expenses.store');
        Route::put('expenses/{expense}', [ExpensesController::class, 'update'])->name('expenses.update');
        Route::delete('expenses/{expense}', [ExpensesController::class, 'destroy'])->name('expenses.destroy');
        Route::get('salaries', [SalariesController::class, 'index'])->name('salaries.index');
        Route::post('salaries', [SalariesController::class, 'storeLegacy'])->name('salaries.store');
        Route::get('salaries/configurations', [SalariesController::class, 'configurations'])->name('salaries.configurations.index');
        Route::post('salaries/configurations', [SalariesController::class, 'storeConfiguration'])->name('salaries.configurations.store');
        Route::put('salaries/configurations/{configuration}', [SalariesController::class, 'updateConfiguration'])->name('salaries.configurations.update');
        Route::delete('salaries/configurations/{configuration}', [SalariesController::class, 'destroyConfiguration'])->name('salaries.configurations.destroy');
        Route::get('salaries/attendance-preview', [SalariesController::class, 'attendancePreview'])->name('salaries.attendance-preview');
        Route::post('salaries/generate', [SalariesController::class, 'generate'])->name('salaries.generate');
        Route::post('salaries/{statement}/payments', [SalariesController::class, 'pay'])->name('salaries.payments.store');
        Route::get('salaries/payments/{payment}/receipt', [SalariesController::class, 'paymentReceipt'])->name('salaries.payments.receipt');
        Route::delete('salaries/{statement}', [SalariesController::class, 'destroy'])->name('salaries.destroy');
        Route::get('salaries/{statement}/print', [SalariesController::class, 'print'])->name('salaries.print');
        Route::get('planifications', [TrainingPlansController::class, 'index'])->name('training-plans.index');
        Route::post('planifications', [TrainingPlansController::class, 'store'])->name('training-plans.store');
        Route::get('planifications/{trainingPlan}', [TrainingPlansController::class, 'show'])->name('training-plans.show');
        Route::put('planifications/{trainingPlan}', [TrainingPlansController::class, 'update'])->name('training-plans.update');
        Route::post('planifications/{trainingPlan}/groupes', [TrainingPlansController::class, 'storeGroup'])->name('training-plans.groups.store');
        Route::put('planifications/{trainingPlan}/groupes/{group}', [TrainingPlansController::class, 'updateGroup'])->name('training-plans.groups.update');
        Route::delete('planifications/{trainingPlan}/groupes/{group}', [TrainingPlansController::class, 'destroyGroup'])->name('training-plans.groups.destroy');
        Route::post('planifications/{trainingPlan}/groupes/{group}/etudiants', [TrainingPlansController::class, 'addStudent'])->name('training-plans.groups.students.store');
        Route::put('planifications/{trainingPlan}/groupes/{group}/inscriptions/{enrollment}/etudiant', [TrainingPlansController::class, 'updateStudent'])->name('training-plans.groups.students.update');
        Route::patch('planifications/{trainingPlan}/groupes/{group}/inscriptions/{enrollment}/deplacer', [TrainingPlansController::class, 'moveStudent'])->name('training-plans.groups.students.move');
        Route::post('planifications/{trainingPlan}/groupes/{group}/seances', [TrainingPlansController::class, 'storeSession'])->name('training-plans.sessions.store');
        Route::put('planifications/{trainingPlan}/groupes/{group}/seances/{session}', [TrainingPlansController::class, 'updateSession'])->name('training-plans.sessions.update');
        Route::delete('planifications/{trainingPlan}/groupes/{group}/seances/{session}', [TrainingPlansController::class, 'destroySession'])->name('training-plans.sessions.destroy');
        Route::patch('planifications/{trainingPlan}/groupes/{group}/seances/{session}/complete', [TrainingPlansController::class, 'completeSession'])->name('training-plans.sessions.complete');
        Route::put('planifications/{trainingPlan}/groupes/{group}/seances/{session}/presences', [TrainingPlansController::class, 'recordAttendance'])->name('training-plans.sessions.attendance');
    });
require __DIR__ . '/settings.php';
require __DIR__ . '/auth.php';
