<script setup lang="ts">
import AdminLayout from '@/layouts/AdminLayout.vue';
import { Head, Link, usePage } from '@inertiajs/vue3';
import { ArrowRight, CalendarDays, CheckCircle2, ChevronRight, CircleAlert, Clock3, CreditCard, GraduationCap, Megaphone, Plus, Settings2, UserX, Users, WalletCards } from 'lucide-vue-next';
import { computed } from 'vue';
interface DashboardData { stats: Record<string, number>; finance: Record<string, number | null>; schedule: { today: any[]; upcoming: any[] }; activities: Array<{ type: string; title: string; date: string }>; currency: { symbol: string; code: string } }
const props = defineProps<{ dashboard: DashboardData | null }>();
const page = usePage();
const user = computed(() => (page.props.auth?.user ?? { name: 'Utilisateur' }) as { name?: string });
const firstName = computed(() => user.value.name?.split(' ')[0] || '');
const d = computed(() => props.dashboard);
const money = (v: number | null | undefined) => `${Number(v ?? 0).toLocaleString('fr-FR')} ${d.value?.currency.symbol ?? 'DZD'}`;
const today = computed(() => new Date().toLocaleDateString('fr-FR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }));
const time = (v: string) => new Date(v).toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
const actions = [{ label: 'Nouvelle inscription', hint: 'Inscrire un nouvel élève', href: '/admin/enrollment-forms', icon: GraduationCap, tone: 'mint' }, { label: 'Ajouter un élève', hint: 'Créer un dossier élève', href: '/admin/students', icon: Users, tone: 'blue' }, { label: 'Encaisser un paiement', hint: 'Paiement des frais de scolarité', href: '/admin/finance', icon: CreditCard, tone: 'rose' }, { label: 'Emploi du temps', hint: 'Voir et gérer les séances', href: '/admin/planifications', icon: CalendarDays, tone: 'purple' }, { label: 'Déclarer une absence', hint: 'Élève ou enseignant', href: '/admin/school-absence', icon: UserX, tone: 'orange' }, { label: 'Envoyer une annonce', hint: 'Informer les parents', href: '/admin/announcements', icon: Megaphone, tone: 'cyan' }];
</script>
<template><Head title="Bienvenue" /><AdminLayout><main class="min-w-0 flex-1 bg-[#f5f9fc] p-4 text-[#19324d] sm:p-6 lg:p-8"><div class="mx-auto max-w-[1500px] space-y-4">
<header class="relative overflow-hidden rounded-2xl border border-sky-100 bg-gradient-to-r from-white via-[#effbff] to-[#e6f7f5] px-6 py-5 shadow-sm"><div class="relative flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-2xl font-extrabold tracking-tight sm:text-3xl">Bonjour {{ firstName }} 👋</h1><p class="mt-1 text-xs capitalize text-slate-500">{{ today }} <span class="mx-2">·</span> Année scolaire 2026-2027 <span class="mx-2">·</span> Site principal</p></div><Link href="/admin/settings" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white/70 px-3 py-2 text-xs font-semibold text-slate-600"><Settings2 class="size-3.5" /> Personnaliser</Link></div></header>
<section v-if="d" class="grid gap-3 lg:grid-cols-[1.6fr_1fr]"><div class="rounded-xl border border-slate-100 bg-white p-4 shadow-sm"><p class="mb-3 text-sm font-bold">Aujourd'hui</p><div class="grid grid-cols-2 gap-3 sm:grid-cols-4"><div v-for="item in [{l:'Absences élèves',v:d.stats.students_absent_today,i:UserX,c:'rose'},{l:'Absence enseignant',v:d.stats.teachers_absent_today,i:UserX,c:'blue'},{l:'Séances aujourd’hui',v:d.schedule.today.length,i:CalendarDays,c:'mint'},{l:'Actions à traiter',v:d.stats.waiting_registrations,i:CircleAlert,c:'orange'}]" :key="item.l" class="flex items-center gap-3"><div :class="`metric-icon ${item.c}`"><component :is="item.i" class="size-4" /></div><div><b class="block text-lg leading-none">{{ item.v }}</b><span class="text-[10px] text-slate-500">{{ item.l }}</span></div></div></div></div><div class="rounded-xl border border-slate-100 bg-white p-4 shadow-sm"><div class="mb-3 flex items-center justify-between"><p class="text-sm font-bold">Cette semaine</p><span class="text-[10px] text-slate-400">VS semaine dernière</span></div><div class="grid grid-cols-3 gap-2 text-center"><div><b class="block text-lg">{{ d.stats.students }}</b><span class="text-[10px] text-slate-500">Élèves actifs</span></div><div><b class="block text-lg">{{ d.stats.monthly_enrollments }}</b><span class="text-[10px] text-slate-500">Nouvelles inscriptions</span></div><div><b class="block text-sm">{{ money(d.finance.collected) }}</b><span class="text-[10px] text-slate-500">Paiements encaissés</span></div></div></div></section>
<section class="rounded-xl border border-slate-100 bg-white p-4 shadow-sm"><div class="mb-3 flex items-center justify-between"><div><h2 class="text-sm font-bold">Actions rapides</h2><p class="text-xs text-slate-400">Accédez rapidement aux opérations les plus courantes</p></div><Plus class="size-4 text-slate-300" /></div><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Link v-for="action in actions" :key="action.label" :href="action.href" class="quick-action" :class="action.tone"><span class="action-icon"><component :is="action.icon" class="size-5" /></span><span><b class="block text-xs">{{ action.label }}</b><small class="block text-[10px] opacity-65">{{ action.hint }}</small></span><ArrowRight class="ml-auto size-4 opacity-60" /></Link></div></section>
<section class="grid gap-4 xl:grid-cols-3"><div class="panel"><div class="panel-title"><span><CircleAlert class="inline size-4 text-rose-500" /> À traiter aujourd'hui</span><Link href="/admin/reports" class="text-[10px] text-blue-500">Voir tout <ArrowRight class="inline size-3" /></Link></div><div v-for="row in [{l:'Absences élèves non justifiées',v:d?.stats.students_absent_today ?? 0,i:UserX},{l:'Paiements en retard',v:d?.finance.overdue ?? 0,i:WalletCards},{l:'Inscriptions à valider',v:d?.stats.waiting_registrations ?? 0,i:GraduationCap}]" :key="row.l" class="list-row"><component :is="row.i" class="size-4 text-slate-400" /><span class="flex-1 text-xs">{{ row.l }}</span><b class="rounded-full bg-rose-50 px-2 py-0.5 text-xs text-rose-500">{{ row.v }}</b><ChevronRight class="size-3 text-slate-300" /></div></div><div class="panel"><div class="panel-title"><span><Clock3 class="inline size-4 text-blue-500" /> Activité récente</span><Link href="/admin/audit" class="text-[10px] text-blue-500">Voir tout <ArrowRight class="inline size-3" /></Link></div><div v-for="activity in (d?.activities ?? []).slice(0,5)" :key="activity.title" class="list-row"><span class="activity-dot"><CheckCircle2 class="size-3" /></span><span class="flex-1 text-xs">{{ activity.title }}</span><small class="text-[10px] text-slate-400">récent</small></div><div v-if="!d?.activities?.length" class="p-6 text-center text-xs text-slate-400">Aucune activité récente</div></div><div class="panel"><div class="panel-title"><span><CalendarDays class="inline size-4 text-blue-500" /> Séances aujourd'hui</span><Link href="/admin/planifications" class="text-[10px] text-blue-500">Voir l'emploi du temps <ArrowRight class="inline size-3" /></Link></div><div v-for="session in (d?.schedule.today ?? []).slice(0,5)" :key="session.id" class="list-row"><b class="w-10 text-[10px] text-blue-600">{{ time(session.starts_at) }}</b><span class="flex-1 text-xs">{{ session.group?.name ?? 'Séance' }}<small class="block text-[10px] text-slate-400">{{ session.group?.plan?.course?.title ?? session.classroom?.name ?? '' }}</small></span><span class="rounded bg-emerald-50 px-2 py-1 text-[10px] text-emerald-600">À venir</span></div><div v-if="!d?.schedule.today?.length" class="p-6 text-center text-xs text-slate-400">Aucune séance prévue aujourd'hui</div></div></section>
</div></main></AdminLayout></template>
<style scoped>
.metric-icon{display:flex;height:2.25rem;width:2.25rem;flex-shrink:0;align-items:center;justify-content:center;border-radius:9999px}.metric-icon.rose{background:#ffe4e6;color:#f43f5e}.metric-icon.blue{background:#dbeafe;color:#3b82f6}.metric-icon.mint{background:#d1fae5;color:#10b981}.metric-icon.orange{background:#ffedd5;color:#f97316}.quick-action{display:flex;min-height:66px;align-items:center;gap:.75rem;border-radius:.5rem;padding:.75rem 1rem;transition:.2s}.quick-action:hover{transform:translateY(-2px);box-shadow:0 4px 10px #cbd5e155}.quick-action.mint{background:#ecfdf5;color:#065f46}.quick-action.blue{background:#eff6ff;color:#1e40af}.quick-action.rose{background:#fff1f2;color:#9f1239}.quick-action.purple{background:#f5f3ff;color:#5b21b6}.quick-action.orange{background:#fff7ed;color:#9a3412}.quick-action.cyan{background:#ecfeff;color:#155e75}.action-icon{display:flex;height:2.5rem;width:2.5rem;flex-shrink:0;align-items:center;justify-content:center;border-radius:9999px;background:#ffffff99}.panel{overflow:hidden;border-radius:.75rem;border:1px solid #f1f5f9;background:#fff;padding:1rem;box-shadow:0 1px 2px #0f172a0a}.panel-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:.75rem;font-size:.875rem;font-weight:700}.list-row{display:flex;min-height:2.75rem;align-items:center;gap:.75rem;border-top:1px solid #f8fafc;padding:.5rem 0}.activity-dot{display:flex;height:1.5rem;width:1.5rem;align-items:center;justify-content:center;border-radius:9999px;background:#eff6ff;color:#3b82f6}
</style>
