<script setup lang="ts">
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Dialog, DialogDescription, DialogFooter, DialogHeader, DialogScrollContent, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AdminLayout from '@/layouts/AdminLayout.vue';
import { Head, router, useForm } from '@inertiajs/vue3';
import { CalendarCheck, Clock3, Lock, RotateCcw, Search, UserCheck, UserX, Users } from 'lucide-vue-next';
import { computed, ref } from 'vue';

const props=defineProps<{sessions:any[];todaySessions:any[];studentRecords:any[];employeeRecords:any[];employees:any[];teachers:any[];filters:any;stats:any}>();
const tab=ref('today');const search=ref('');const sheetOpen=ref(false);const teacherOpen=ref(false);const employeeOpen=ref(false);const selected=ref<any>(null);const selectedStudentIds=ref<number[]>([]);const selectedTeacherSessionIds=ref<number[]>([]);
const attendance=useForm({records:[] as any[],correction_reason:''});
const teacher=useForm({status:'present',actual_teacher_id:'',worked_minutes:0,is_justified:false,justification:'',notes:'',correction_reason:''});
const teachersBulk=useForm({session_ids:[] as number[],status:'present',justification:''});
const employee=useForm({staff_id:'',attendance_date:new Date().toISOString().slice(0,10),status:'present',check_in:'',check_out:'',worked_minutes:0,is_justified:false,justification:'',notes:'',correction_reason:''});
const reopen=useForm({reason:''});
const statusLabel:any={present:'Présent',absent:'Absent',late:'Retard',excused:'Absence excusée',left_early:'Départ anticipé',replaced:'Remplacé',cancelled:'Annulée',leave:'Congé'};
const tone:any={present:'bg-emerald-100 text-emerald-700',absent:'bg-red-100 text-red-700',late:'bg-amber-100 text-amber-700',excused:'bg-blue-100 text-blue-700',left_early:'bg-orange-100 text-orange-700'};
const visibleRecords=computed(()=>{const q=search.value.toLowerCase();return props.studentRecords.filter((r:any)=>!q||`${r.student.first_name} ${r.student.last_name} ${r.session.title} ${r.session.group?.plan?.course?.title}`.toLowerCase().includes(q));});
function openSheet(session:any){selected.value=session;const current=Object.fromEntries(session.attendances.map((a:any)=>[a.student_id,a]));attendance.records=session.group.enrollments.map((e:any)=>{const a=current[e.student_id];return {student_id:e.student_id,student:e.student,status:a?.status??'present',is_justified:a?.is_justified??false,justification:a?.justification??'',notes:a?.notes??''}});selectedStudentIds.value=attendance.records.map((r:any)=>r.student_id);attendance.correction_reason='';sheetOpen.value=true;}
function toggleStudent(id:number){selectedStudentIds.value=selectedStudentIds.value.includes(id)?selectedStudentIds.value.filter(x=>x!==id):[...selectedStudentIds.value,id];}
function toggleAllStudents(){selectedStudentIds.value=selectedStudentIds.value.length===attendance.records.length?[]:attendance.records.map((r:any)=>r.student_id);}
function applyStudentStatus(status:string){attendance.records.filter((r:any)=>selectedStudentIds.value.includes(r.student_id)).forEach((r:any)=>{r.status=status;r.is_justified=status==='excused';if(status==='present')r.justification='';});}
function saveSheet(){attendance.put(`/admin/attendance/sessions/${selected.value.id}/students`,{preserveScroll:true,onSuccess:()=>sheetOpen.value=false});}
function validateSheet(s:any){router.patch(`/admin/attendance/sessions/${s.id}/validate`,{},{preserveScroll:true});}
function reopenSheet(s:any){const reason=window.prompt('Motif obligatoire de réouverture :');if(reason)router.patch(`/admin/attendance/sessions/${s.id}/reopen`,{reason},{preserveScroll:true});}
function openTeacher(s:any){selected.value=s;const a=s.teacher_attendance;teacher.defaults({status:a?.status??'present',actual_teacher_id:String(a?.actual_teacher_id??s.teacher_id),worked_minutes:a?.worked_minutes??Math.round((new Date(s.ends_at).getTime()-new Date(s.starts_at).getTime())/60000),is_justified:a?.is_justified??false,justification:a?.justification??'',notes:a?.notes??'',correction_reason:''});teacher.reset();teacherOpen.value=true;}
function saveTeacher(){teacher.put(`/admin/attendance/sessions/${selected.value.id}/teacher`,{preserveScroll:true,onSuccess:()=>teacherOpen.value=false});}
function toggleTeacherSession(id:number){selectedTeacherSessionIds.value=selectedTeacherSessionIds.value.includes(id)?selectedTeacherSessionIds.value.filter(x=>x!==id):[...selectedTeacherSessionIds.value,id];}
function toggleAllTeacherSessions(){const editable=props.sessions.filter((s:any)=>!s.teacher_attendance?.validated_at).map((s:any)=>s.id);selectedTeacherSessionIds.value=selectedTeacherSessionIds.value.length===editable.length?[]:editable;}
function applyTeachersBulk(status:string){teachersBulk.session_ids=[...selectedTeacherSessionIds.value];teachersBulk.status=status;teachersBulk.put('/admin/attendance/teachers/bulk',{preserveScroll:true,onSuccess:()=>selectedTeacherSessionIds.value=[]});}
function saveEmployee(){employee.put('/admin/attendance/employees',{preserveScroll:true,onSuccess:()=>employeeOpen.value=false});}
const date=(v:string)=>new Date(v).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'});
</script>

<template><Head title="Présences et pointage"/><AdminLayout><main class="flex-1 space-y-6 p-4 sm:p-6 lg:p-8">
 <header><h1 class="text-2xl font-bold">Présences et pointage</h1><p class="text-muted-foreground">Présences liées aux séances et pointage quotidien du personnel.</p></header>
 <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
  <div class="rounded-xl border bg-card p-4"><UserCheck class="size-5 text-emerald-600"/><b class="mt-2 block text-2xl">{{stats.present_today}}</b><span class="text-xs text-muted-foreground">Étudiants présents aujourd’hui</span></div>
  <div class="rounded-xl border bg-card p-4"><UserX class="size-5 text-red-600"/><b class="mt-2 block text-2xl">{{stats.absent_today}}</b><span class="text-xs text-muted-foreground">Étudiants absents</span></div>
  <div class="rounded-xl border bg-card p-4"><Users class="size-5 text-red-600"/><b class="mt-2 block text-2xl">{{stats.teachers_absent}}</b><span class="text-xs text-muted-foreground">Enseignants absents</span></div>
  <div class="rounded-xl border bg-card p-4"><Clock3 class="size-5 text-amber-600"/><b class="mt-2 block text-2xl">{{stats.missing}}</b><span class="text-xs text-muted-foreground">Feuilles manquantes</span></div>
  <div class="rounded-xl border bg-card p-4"><CalendarCheck class="size-5 text-primary"/><b class="mt-2 block text-2xl">{{stats.global_rate??'—'}}%</b><span class="text-xs text-muted-foreground">Taux global</span></div>
 </section>
 <nav class="flex flex-wrap gap-2 border-b pb-3"><Button v-for="item in [{id:'today',label:'Aujourd’hui'},{id:'students',label:'Étudiants'},{id:'teachers',label:'Enseignants'},{id:'employees',label:'Employés'}]" :key="item.id" :variant="tab===item.id?'default':'ghost'" @click="tab=item.id">{{item.label}}</Button></nav>

 <section v-if="tab==='today'" class="space-y-3">
  <article v-for="s in todaySessions" :key="s.id" class="grid gap-4 rounded-xl border bg-card p-4 lg:grid-cols-[1fr_auto] lg:items-center">
   <div><div class="flex flex-wrap items-center gap-2"><h2 class="font-semibold">{{s.group.plan.course.title}} · {{s.group.name}}</h2><span class="rounded-full px-2 py-0.5 text-xs" :class="s.attendance_status==='validated'?'bg-emerald-100 text-emerald-700':s.attendance_status==='completed'?'bg-blue-100 text-blue-700':'bg-amber-100 text-amber-700'">{{s.attendance_status==='validated'?'Validée':s.attendance_status==='completed'?'Saisie':'À saisir'}}</span></div><p class="text-sm text-muted-foreground">{{date(s.starts_at)}} · {{s.classroom?.name}} · {{s.teacher.name}}</p><p class="mt-1 text-sm">{{s.attendances.filter((a:any)=>['present','late'].includes(a.status)).length}} présents · {{s.attendances.filter((a:any)=>a.status==='absent').length}} absents · Enseignant: {{statusLabel[s.teacher_attendance?.status]??'Non pointé'}}</p></div>
   <div class="flex flex-wrap gap-2"><Button size="sm" variant="outline" @click="openTeacher(s)">Pointage enseignant</Button><Button size="sm" @click="openSheet(s)">Feuille étudiants</Button><Button v-if="s.attendance_status==='completed'" size="sm" variant="outline" @click="validateSheet(s)"><Lock class="mr-2 size-4"/>Valider</Button><Button v-if="s.attendance_status==='validated'" size="sm" variant="outline" @click="reopenSheet(s)"><RotateCcw class="mr-2 size-4"/>Rouvrir</Button></div>
  </article><p v-if="!todaySessions.length" class="rounded-xl border p-8 text-center text-muted-foreground">Aucune séance aujourd’hui.</p>
 </section>

 <section v-else-if="tab==='students'" class="space-y-3"><div class="relative max-w-md"><Search class="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input v-model="search" class="pl-9" placeholder="Rechercher étudiant, formation ou séance…"/></div><div class="overflow-x-auto rounded-xl border"><table class="w-full text-sm"><thead class="bg-muted/40 text-left"><tr><th class="p-3">Étudiant</th><th class="p-3">Formation / groupe</th><th class="p-3">Séance</th><th class="p-3">Enseignant</th><th class="p-3">Statut</th><th class="p-3">Justification</th></tr></thead><tbody><tr v-for="r in visibleRecords" :key="r.id" class="border-t"><td class="p-3 font-medium">{{r.student.first_name}} {{r.student.last_name}}</td><td class="p-3">{{r.session.group.plan.course.title}} · {{r.session.group.name}}</td><td class="p-3">{{date(r.session.starts_at)}}</td><td class="p-3">{{r.session.teacher?.name}}</td><td class="p-3"><span class="rounded-full px-2 py-1 text-xs" :class="tone[r.status]">{{statusLabel[r.status]}}</span></td><td class="p-3">{{r.justification||r.notes||'—'}}</td></tr></tbody></table></div></section>
 <section v-else-if="tab==='teachers'" class="space-y-3"><div class="flex flex-wrap items-center gap-2 rounded-xl border bg-muted/20 p-3"><Button size="sm" variant="outline" @click="toggleAllTeacherSessions">{{selectedTeacherSessionIds.length?'Désélectionner':'Sélectionner tout'}}</Button><span class="mr-auto text-sm text-muted-foreground">{{selectedTeacherSessionIds.length}} séance(s) sélectionnée(s)</span><Button size="sm" :disabled="!selectedTeacherSessionIds.length" @click="applyTeachersBulk('present')">Présents</Button><Button size="sm" variant="destructive" :disabled="!selectedTeacherSessionIds.length" @click="applyTeachersBulk('absent')">Absents</Button><Button size="sm" variant="outline" :disabled="!selectedTeacherSessionIds.length" @click="applyTeachersBulk('late')">En retard</Button><Button size="sm" variant="outline" :disabled="!selectedTeacherSessionIds.length" @click="applyTeachersBulk('excused')">Excusés</Button></div><article v-for="s in sessions" :key="s.id" class="grid grid-cols-[28px_1fr_auto] items-center gap-3 rounded-xl border bg-card p-4" :class="selectedTeacherSessionIds.includes(s.id)?'ring-1 ring-primary':''"><input type="checkbox" class="size-4" :checked="selectedTeacherSessionIds.includes(s.id)" :disabled="Boolean(s.teacher_attendance?.validated_at)" @change="toggleTeacherSession(s.id)"/><div><b>{{s.teacher.name}}</b><p class="text-sm text-muted-foreground">{{s.group.plan.course.title}} · {{s.group.name}} · {{date(s.starts_at)}}</p><p class="text-sm">{{statusLabel[s.teacher_attendance?.status]??'Non pointé'}}<span v-if="s.teacher_attendance"> · {{s.teacher_attendance.worked_minutes}} min</span><span v-if="s.teacher_attendance?.actual_teacher"> · Réalisée par {{s.teacher_attendance.actual_teacher.name}}</span></p></div><Button size="sm" variant="outline" @click="openTeacher(s)">{{s.teacher_attendance?'Corriger':'Pointer'}}</Button></article></section>
 <section v-else class="space-y-4"><Button @click="employeeOpen=true">Ajouter un pointage employé</Button><div class="overflow-x-auto rounded-xl border"><table class="w-full text-sm"><thead class="bg-muted/40 text-left"><tr><th class="p-3">Employé</th><th class="p-3">Fonction</th><th class="p-3">Date</th><th class="p-3">Statut</th><th class="p-3">Horaires</th><th class="p-3">Durée</th></tr></thead><tbody><tr v-for="r in employeeRecords" :key="r.id" class="border-t"><td class="p-3 font-medium">{{r.staff.name}}</td><td class="p-3">{{r.staff.employee_type.name}}</td><td class="p-3">{{r.attendance_date}}</td><td class="p-3">{{statusLabel[r.status]}}</td><td class="p-3">{{r.check_in||'—'}} → {{r.check_out||'—'}}</td><td class="p-3">{{r.worked_minutes}} min</td></tr></tbody></table></div></section>

 <Dialog v-model:open="sheetOpen"><DialogScrollContent class="max-w-4xl"><DialogHeader><DialogTitle>Feuille de présence · {{selected?.title}}</DialogTitle><DialogDescription>{{selected?.group?.plan?.course?.title}} · {{selected?.group?.name}}. Sélectionnez plusieurs étudiants puis appliquez un statut.</DialogDescription></DialogHeader><form class="space-y-4" @submit.prevent="saveSheet"><div class="flex flex-wrap items-center gap-2 rounded-lg border bg-muted/20 p-3"><Button type="button" size="sm" variant="outline" @click="toggleAllStudents">{{selectedStudentIds.length===attendance.records.length?'Tout désélectionner':'Tout sélectionner'}}</Button><span class="mr-auto text-sm text-muted-foreground">{{selectedStudentIds.length}} sélectionné(s)</span><Button type="button" size="sm" :disabled="!selectedStudentIds.length" @click="applyStudentStatus('present')">Présents</Button><Button type="button" size="sm" variant="destructive" :disabled="!selectedStudentIds.length" @click="applyStudentStatus('absent')">Absents</Button><Button type="button" size="sm" variant="outline" :disabled="!selectedStudentIds.length" @click="applyStudentStatus('late')">En retard</Button><Button type="button" size="sm" variant="outline" :disabled="!selectedStudentIds.length" @click="applyStudentStatus('excused')">Excusés</Button><span v-if="selected?.attendance_locked_at" class="text-sm text-amber-700"><Lock class="mr-1 inline size-4"/>Correction administrateur</span></div><div class="space-y-2"><div v-for="r in attendance.records" :key="r.student_id" class="grid gap-2 rounded-lg border p-3 md:grid-cols-[28px_1fr_160px]" :class="selectedStudentIds.includes(r.student_id)?'bg-primary/5':''"><input type="checkbox" class="mt-2 size-4" :checked="selectedStudentIds.includes(r.student_id)" @change="toggleStudent(r.student_id)"/><div class="flex items-center gap-3"><img v-if="r.student.photo_url" :src="r.student.photo_url" class="size-9 rounded-full object-cover"/><b>{{r.student.first_name}} {{r.student.last_name}}</b></div><select v-model="r.status" class="h-9 rounded-md border bg-background px-2"><option v-for="(label,key) in statusLabel" v-show="['present','absent','late','excused','left_early'].includes(String(key))" :key="key" :value="key">{{label}}</option></select><div v-if="['absent','excused'].includes(r.status)" class="md:col-span-3"><Input v-model="r.justification" placeholder="Justification / motif"/></div></div></div><div v-if="selected?.attendance_locked_at"><Label>Motif de correction</Label><Input v-model="attendance.correction_reason" required/></div><InputError :message="Object.values(attendance.errors)[0]"/><DialogFooter><Button :disabled="attendance.processing">Enregistrer</Button></DialogFooter></form></DialogScrollContent></Dialog>
 <Dialog v-model:open="teacherOpen"><DialogScrollContent><DialogHeader><DialogTitle>Pointage enseignant</DialogTitle><DialogDescription>Le formateur planifié reste conservé même en cas de remplacement.</DialogDescription></DialogHeader><form class="space-y-4" @submit.prevent="saveTeacher"><div><Label>Statut</Label><select v-model="teacher.status" class="mt-1 h-9 w-full rounded-md border bg-background px-3"><option value="present">Présent</option><option value="absent">Absent</option><option value="late">Retard</option><option value="excused">Excusé</option><option value="replaced">Remplacé</option><option value="cancelled">Séance annulée</option></select></div><div v-if="teacher.status==='replaced'"><Label>Enseignant remplaçant</Label><select v-model="teacher.actual_teacher_id" required class="mt-1 h-9 w-full rounded-md border bg-background px-3"><option v-for="t in teachers" :key="t.id" :value="String(t.id)">{{t.name}}</option></select></div><div><Label>Durée travaillée validée (minutes)</Label><Input v-model="teacher.worked_minutes" type="number" min="0"/></div><div><Label>Justification</Label><Input v-model="teacher.justification"/></div><div v-if="selected?.teacher_attendance?.validated_at"><Label>Motif de correction</Label><Input v-model="teacher.correction_reason" required/></div><InputError :message="Object.values(teacher.errors)[0]"/><DialogFooter><Button :disabled="teacher.processing">Enregistrer et valider</Button></DialogFooter></form></DialogScrollContent></Dialog>
 <Dialog v-model:open="employeeOpen"><DialogScrollContent><DialogHeader><DialogTitle>Pointage employé</DialogTitle><DialogDescription>Pointage quotidien hors séances d’enseignement.</DialogDescription></DialogHeader><form class="space-y-4" @submit.prevent="saveEmployee"><div><Label>Employé</Label><select v-model="employee.staff_id" required class="mt-1 h-9 w-full rounded-md border bg-background px-3"><option value="" disabled>Sélectionner</option><option v-for="e in employees" :key="e.id" :value="String(e.id)">{{e.name}} · {{e.employee_type.name}}</option></select></div><div class="grid grid-cols-2 gap-3"><div><Label>Date</Label><Input v-model="employee.attendance_date" type="date" required/></div><div><Label>Statut</Label><select v-model="employee.status" class="mt-1 h-9 w-full rounded-md border bg-background px-3"><option value="present">Présent</option><option value="absent">Absent</option><option value="late">Retard</option><option value="excused">Excusé</option><option value="leave">Congé</option></select></div><div><Label>Arrivée</Label><Input v-model="employee.check_in" type="time"/></div><div><Label>Départ</Label><Input v-model="employee.check_out" type="time"/></div></div><div><Label>Minutes travaillées</Label><Input v-model="employee.worked_minutes" type="number" min="0"/></div><div><Label>Justification / notes</Label><Input v-model="employee.justification"/></div><InputError :message="Object.values(employee.errors)[0]"/><DialogFooter><Button :disabled="employee.processing">Enregistrer</Button></DialogFooter></form></DialogScrollContent></Dialog>
</main></AdminLayout></template>
