<script setup lang="ts">
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import AdminLayout from '@/layouts/AdminLayout.vue'; import { Head, Link, router } from '@inertiajs/vue3'; import { Eye, Search, X } from 'lucide-vue-next'; import { reactive, ref } from 'vue';
const props = defineProps<{ inscriptions: any; capacity: any[]; academicYears: any[]; campaigns: any[]; levels: any[]; statuses: string[]; filters: any }>();
const filters = reactive({ search: props.filters.search || '', academic_year_id: props.filters.academic_year_id || '', campaign_id: props.filters.campaign_id || '', school_level_id: props.filters.school_level_id || '', status: props.filters.status || '' }); const selected = ref<any>(null); const notes = ref('');
function apply() { router.get('/admin/school-inscriptions', filters, { preserveState: true, replace: true }); }
function status(item:any, value:string) { router.patch(`/admin/school-inscriptions/${item.id}/status`, { status: value, review_notes: notes.value || null }, { preserveScroll: true, onSuccess: () => { selected.value = null; notes.value = ''; } }); }
const labels:Record<string,string>={pending:'En attente',accepted:'Acceptée',rejected:'Rejetée',waiting_list:"Liste d’attente",cancelled:'Annulée'};
</script>
<template><AdminLayout><Head title="Demandes d'inscription"/><main class="flex-1 space-y-6 p-4 sm:p-6 lg:p-8"><header><h1 class="text-2xl font-semibold">Demandes d’inscription scolaire</h1><p class="text-sm text-muted-foreground">Examinez les dossiers sans affecter les élèves aux groupes.</p></header>
<section class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><article v-for="c in capacity" :key="c.id" class="rounded-xl border bg-white p-4"><p class="truncate text-xs text-slate-500">{{ c.campaign.title }}</p><h2 class="mt-1 font-semibold">{{ c.level.name }}</h2><p class="mt-2 text-xl font-bold text-primary">{{ c.accepted_inscriptions_count }} / {{ c.max_places ?? '∞' }} <small class="text-xs font-normal">acceptés</small></p></article></section>
<form class="grid gap-2 rounded-xl border bg-white p-4 md:grid-cols-6" @submit.prevent="apply"><div class="relative md:col-span-2"><Search class="absolute left-3 top-3 size-4 text-slate-400"/><Input v-model="filters.search" class="pl-9" placeholder="Élève, parent, e-mail…"/></div><select v-model="filters.academic_year_id" class="rounded-md border px-2 text-sm"><option value="">Toutes les années</option><option v-for="x in academicYears" :value="x.id">{{x.name}}</option></select><select v-model="filters.campaign_id" class="rounded-md border px-2 text-sm"><option value="">Toutes les campagnes</option><option v-for="x in campaigns" :value="x.id">{{x.title}}</option></select><select v-model="filters.school_level_id" class="rounded-md border px-2 text-sm"><option value="">Tous les niveaux</option><option v-for="x in levels" :value="x.id">{{x.name}}</option></select><div class="flex gap-2"><select v-model="filters.status" class="min-w-0 flex-1 rounded-md border px-2 text-sm"><option value="">Tous statuts</option><option v-for="x in statuses" :value="x">{{labels[x]}}</option></select><Button size="sm">Filtrer</Button></div></form>
<div class="overflow-x-auto rounded-xl border bg-white"><table class="w-full text-sm"><thead class="bg-slate-50 text-left"><tr><th class="p-3">Élève</th><th class="p-3">Parent</th><th class="p-3">Année / campagne</th><th class="p-3">Niveau</th><th class="p-3">Statut</th><th class="p-3"></th></tr></thead><tbody><tr v-for="item in inscriptions.data" :key="item.id" class="border-t"><td class="p-3 font-medium">{{item.student.first_name}} {{item.student.last_name}}<small class="block font-normal text-slate-500">{{item.student.email || item.student.phone}}</small></td><td class="p-3">{{item.parent.first_name}} {{item.parent.last_name}}<small class="block text-slate-500">{{item.parent.user?.email || item.parent.phone}}</small></td><td class="p-3">{{item.academic_year.name}}<small class="block text-slate-500">{{item.campaign.title}}</small></td><td class="p-3">{{item.level.name}}</td><td class="p-3"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs">{{labels[item.status]}}</span></td><td class="p-3"><Button size="icon" variant="ghost" @click="selected=item"><Eye class="size-4"/></Button></td></tr><tr v-if="!inscriptions.data.length"><td colspan="6" class="p-12 text-center text-slate-500">Aucune demande trouvée.</td></tr></tbody></table></div><nav class="flex justify-center gap-1"><Link v-for="l in inscriptions.links" :href="l.url || '#'" class="rounded border px-3 py-1 text-sm" :class="{'bg-primary text-white':l.active,'pointer-events-none opacity-40':!l.url}" v-html="l.label"/></nav>
</main><div v-if="selected" class="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" @click.self="selected=null"><section class="w-full max-w-xl rounded-2xl bg-white p-6"><div class="flex justify-between"><h2 class="text-xl font-semibold">Dossier d’inscription</h2><button @click="selected=null"><X/></button></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><div class="rounded-lg bg-slate-50 p-4"><b>Élève</b><p>{{selected.student.first_name}} {{selected.student.last_name}}</p><p>{{selected.student.birth_date}}</p><p>{{selected.student.email}}</p><p>{{selected.student.phone}}</p><p>{{selected.student.address}}</p></div><div class="rounded-lg bg-slate-50 p-4"><b>Parent / tuteur</b><p>{{selected.parent.first_name}} {{selected.parent.last_name}}</p><p>{{selected.parent.relationship}}</p><p>{{selected.parent.user?.email}}</p><p>{{selected.parent.phone}}</p></div></div><textarea v-model="notes" class="mt-4 min-h-20 w-full rounded-md border p-3" placeholder="Note de décision (facultative)"/><div class="mt-4 flex flex-wrap justify-end gap-2"><Button variant="outline" @click="status(selected,'cancelled')">Annuler</Button><Button variant="outline" @click="status(selected,'waiting_list')">Liste d’attente</Button><Button variant="destructive" @click="status(selected,'rejected')">Rejeter</Button><Button @click="status(selected,'accepted')">Accepter</Button></div></section></div></AdminLayout></template>
