<script setup lang="ts">
import AnnouncementViewer from '@/components/announcements/AnnouncementViewer.vue';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Dialog,DialogDescription,DialogFooter,DialogHeader,DialogScrollContent,DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label';
import FileUpload from '@/components/ViltFilePond/FileUpload.vue';
import { appConfirm } from '@/composables/useAppDialog'; import AdminLayout from '@/layouts/AdminLayout.vue';
import { Head, router, useForm } from '@inertiajs/vue3';
import { Bell, Eye, EyeOff, ImageIcon, Mail, Megaphone, Plus, Send, Smartphone, Trash2, Users } from 'lucide-vue-next';
import { computed, nextTick, ref } from 'vue';
const props=defineProps<{cycles:Array<{id:number;name:string;code:string}>;announcements:{data:any[];links:any[]}}>();
const createOpen=ref(false),previewOpen=ref(false),selected=ref<any>(null),posterFolders=ref<string[]>([]),posterPreview=ref<string|null>(null),uploading=ref(false);
const previewingDraft=ref(false);
const form=useForm({title:'',message:'',delivery:'account',target:'all',status:'draft',cycle_ids:[] as number[],poster_temp_folders:[] as string[]});
const draftPreview=computed(()=>({title:form.title||'Titre de votre annonce',message:form.message||'Le contenu de votre annonce apparaîtra ici.',poster_url:posterPreview.value,published_at:null}));
function openCreate(){form.reset();form.clearErrors();posterFolders.value=[];posterPreview.value=null;createOpen.value=true}
function submit(status:'draft'|'published'){if(uploading.value)return;form.status=status;form.poster_temp_folders=[...posterFolders.value];form.post('/admin/announcements',{preserveScroll:true,onSuccess:()=>createOpen.value=false})}
function posterSelected(payload:any){const file=payload?.file??payload;if(file instanceof File){if(posterPreview.value)URL.revokeObjectURL(posterPreview.value);posterPreview.value=URL.createObjectURL(file)}}
function preview(a:any){previewingDraft.value=false;selected.value=a;previewOpen.value=true}
async function previewForm(){previewingDraft.value=true;selected.value={...draftPreview.value};createOpen.value=false;await nextTick();previewOpen.value=true}
async function closePreview(){previewOpen.value=false;if(previewingDraft.value){await nextTick();createOpen.value=true}}
function setStatus(a:any,status:'published'|'unpublished'){router.patch(`/admin/announcements/${a.id}/status`,{status},{preserveScroll:true})}
async function unpublish(a:any){if(await appConfirm('Les parents ne pourront plus consulter cette annonce. Vous pourrez la republier plus tard.',{title:'Dépublier cette annonce ?',confirmText:'Dépublier',tone:'warning'}))setStatus(a,'unpublished')}
async function remove(a:any){if(await appConfirm('Cette action supprime définitivement l’annonce et son affiche.',{title:'Supprimer cette annonce ?',confirmText:'Supprimer',tone:'danger'}))router.delete(`/admin/announcements/${a.id}`,{preserveScroll:true})}
const badge=(s:string)=>s==='published'?'Publiée':s==='unpublished'?'Dépubliée':'Brouillon'; const date=(v:string)=>new Date(v).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'});
</script>
<template><Head title="Annonces parents"/><AdminLayout><main class="mx-auto w-full max-w-7xl px-1 pb-12 sm:px-3 lg:px-5">
<section class="mb-8 overflow-hidden rounded-3xl bg-gradient-to-r from-slate-950 via-slate-900 to-teal-950 p-7 text-white shadow-xl sm:p-10"><div class="flex flex-col gap-7 sm:flex-row sm:items-end sm:justify-between"><div><div class="mb-4 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-semibold"><Megaphone class="size-4"/>Communication école–parents</div><h1 class="text-3xl font-black sm:text-5xl">Annonces parents</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-slate-300 sm:text-base">Créez, prévisualisez et publiez des communications claires auprès de tous les parents ou de cycles précis.</p></div><Button class="h-12 shrink-0 rounded-xl px-6 text-base" @click="openCreate"><Plus class="mr-2 size-5"/>Nouvelle annonce</Button></div></section>
<div class="mb-5"><h2 class="text-2xl font-bold">Toutes les annonces</h2><p class="text-sm text-slate-500">Brouillons, publications actives et annonces dépubliées</p></div>
<section v-if="announcements.data.length" class="grid gap-6 md:grid-cols-2 xl:grid-cols-3"><article v-for="a in announcements.data" :key="a.id" class="group overflow-hidden rounded-3xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl">
<button class="block h-60 w-full overflow-hidden text-left" @click="preview(a)"><img v-if="a.poster_url" :src="a.poster_url" :alt="a.title" class="h-full w-full object-cover transition duration-500 group-hover:scale-105"><div v-else class="grid h-full place-items-center bg-gradient-to-br from-primary via-teal-500 to-cyan-700 p-7 text-center text-white"><div><Bell class="mx-auto mb-3 size-8 opacity-75"/><h3 class="line-clamp-4 text-3xl font-black leading-tight">{{a.title}}</h3></div></div></button>
<div class="p-5"><div class="mb-3 flex items-center justify-between gap-2"><span class="rounded-full px-2.5 py-1 text-xs font-bold" :class="a.status==='published'?'bg-emerald-100 text-emerald-700':a.status==='unpublished'?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-700'">{{badge(a.status)}}</span><span class="text-xs text-slate-400">{{date(a.created_at)}}</span></div><h3 class="line-clamp-2 text-xl font-bold">{{a.title}}</h3><p class="mt-2 line-clamp-3 min-h-[3.75rem] whitespace-pre-line text-sm leading-5 text-slate-600">{{a.message}}</p><div v-if="a.account_recipient_count>0" class="mt-4 rounded-xl bg-slate-50 p-3"><div class="flex items-center justify-between text-sm"><span class="flex items-center font-medium text-slate-600"><Users class="mr-2 size-4"/>Parents ayant vu</span><strong class="text-primary">{{a.seen_count}} / {{a.account_recipient_count}}</strong></div><div class="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-200"><div class="h-full rounded-full bg-primary transition-all" :style="{width:`${Math.round((a.seen_count/a.account_recipient_count)*100)}%`}"/></div></div><div v-else-if="a.status==='published'" class="mt-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-500">Diffusion par e-mail uniquement · lecture non mesurable</div><div class="mt-4 flex items-center justify-between border-t pt-4"><span class="text-xs text-slate-500">{{a.recipient_count}} destinataire(s)</span><div class="flex gap-1"><Button size="icon" variant="ghost" @click="preview(a)"><Eye class="size-4"/></Button><Button v-if="a.status!=='published'" size="sm" variant="outline" @click="setStatus(a,'published')"><Send class="mr-1 size-4"/>Publier</Button><Button v-else size="sm" variant="outline" class="border-amber-300 text-amber-700 hover:bg-amber-50" @click="unpublish(a)"><EyeOff class="mr-1 size-4"/>Dépublier</Button><Button size="icon" variant="ghost" class="text-rose-600" @click="remove(a)"><Trash2 class="size-4"/></Button></div></div></div></article></section>
<section v-else class="rounded-3xl border border-dashed bg-white px-6 py-20 text-center"><span class="mx-auto grid size-16 place-items-center rounded-2xl bg-primary/10 text-primary"><Megaphone class="size-8"/></span><h2 class="mt-5 text-xl font-bold">Commencez votre première annonce</h2><p class="mt-2 text-slate-500">Créez un brouillon ou publiez directement auprès des parents.</p><Button class="mt-6" @click="openCreate"><Plus class="mr-2 size-4"/>Nouvelle annonce</Button></section></main>
<Dialog v-model:open="createOpen"><DialogScrollContent class="max-w-3xl"><DialogHeader><DialogTitle>Nouvelle annonce</DialogTitle><DialogDescription>Préparez votre message, choisissez son audience puis enregistrez-le ou publiez-le.</DialogDescription></DialogHeader><form class="space-y-6" @submit.prevent="submit('draft')"><div v-if="form.hasErrors" class="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><p class="font-bold">L’annonce n’a pas pu être enregistrée.</p><ul class="mt-1 list-disc pl-5"><li v-for="(error,key) in form.errors" :key="key">{{error}}</li></ul></div><div><Label>Titre de l’annonce</Label><Input v-model="form.title" class="mt-2" placeholder="Ex. Journée portes ouvertes"/><InputError :message="form.errors.title"/></div><div><Label>Message</Label><textarea v-model="form.message" rows="7" class="mt-2 w-full rounded-xl border bg-background px-4 py-3 text-sm leading-6" placeholder="Rédigez votre message…"/><InputError :message="form.errors.message"/></div>
<div class="grid gap-5 sm:grid-cols-2"><div><Label>Destinataires</Label><div class="mt-2 space-y-2"><label class="flex rounded-xl border p-3"><input v-model="form.target" type="radio" value="all" class="mr-3">Tous les parents</label><label class="flex rounded-xl border p-3"><input v-model="form.target" type="radio" value="cycles" class="mr-3">Cycles spécifiques</label></div></div><div><Label>Canal</Label><div class="mt-2 space-y-2"><label class="flex rounded-xl border p-3"><input v-model="form.delivery" type="radio" value="account" class="mr-3"><Smartphone class="mr-2 size-4"/>Compte parent</label><label class="flex rounded-xl border p-3"><input v-model="form.delivery" type="radio" value="email" class="mr-3"><Mail class="mr-2 size-4"/>E-mail</label><label class="flex rounded-xl border p-3"><input v-model="form.delivery" type="radio" value="both" class="mr-3">Compte et e-mail</label></div></div></div>
<div v-if="form.target==='cycles'" class="rounded-2xl bg-slate-50 p-4"><Label>Cycles concernés</Label><div class="mt-3 flex flex-wrap gap-2"><label v-for="c in cycles" :key="c.id" class="rounded-full border bg-white px-4 py-2 text-sm"><input v-model="form.cycle_ids" type="checkbox" :value="c.id" class="mr-2">{{c.name}}</label></div><InputError :message="form.errors.cycle_ids"/></div>
<div><div class="mb-2 flex items-center gap-2"><ImageIcon class="size-4"/><Label>Affiche (facultative)</Label></div><FileUpload v-model="posterFolders" :allow-multiple="false" :max-files="1" :allowed-file-types="['image/jpeg','image/png','image/webp']" collection="poster" @file-selected="posterSelected" @file-removed="posterPreview=null" @upload-started="uploading=true" @upload-finished="uploading=false"/><p v-if="uploading" class="mt-2 text-xs font-medium text-primary">Chargement de l’affiche en cours…</p><InputError :message="form.errors.poster_temp_folders"/></div>
<DialogFooter class="gap-2"><Button type="button" variant="outline" :disabled="uploading" @click="previewForm"><Eye class="mr-2 size-4"/>Tester l’affichage</Button><Button type="submit" variant="secondary" :disabled="form.processing||uploading">Enregistrer en brouillon</Button><Button type="button" :disabled="form.processing||uploading" @click="submit('published')"><Send class="mr-2 size-4"/>{{form.processing?'Publication…':'Publier'}}</Button></DialogFooter></form></DialogScrollContent></Dialog>
<AnnouncementViewer :open="previewOpen" :announcement="selected" preview @close="closePreview"/>
</AdminLayout></template>
