<!doctype html><html lang="fr"><head><meta charset="utf-8"><style>
@page{margin:0}*{box-sizing:border-box}body{margin:0;font-family:DejaVu Sans,sans-serif;color:#17212b}.page{position:relative;width:260mm;height:165mm;padding:12mm;background:#fff}.outer{position:relative;height:160mm;border:1.2mm solid #173f52;padding:3mm}.inner{position:relative;height:136mm;border:.35mm solid {{ $school->primary_color ?: '#167d78' }};padding:10mm 16mm;text-align:center}.corner{position:absolute;width:18mm;height:18mm;border-color:{{ $school->primary_color ?: '#167d78' }}}.tl{left:4mm;top:4mm;border-left:1mm solid;border-top:1mm solid}.tr{right:4mm;top:4mm;border-right:1mm solid;border-top:1mm solid}.bl{left:4mm;bottom:4mm;border-left:1mm solid;border-bottom:1mm solid}.br{right:4mm;bottom:4mm;border-right:1mm solid;border-bottom:1mm solid}.logo{max-height:18mm;max-width:34mm}.school{margin-top:1mm;font-size:18px;font-weight:bold;color:#173f52}.legal{font-size:8px;color:#687980}.kicker{margin-top:4mm;font-size:9px;text-transform:uppercase;letter-spacing:3px;color:{{ $school->primary_color ?: '#167d78' }}}h1{margin:2mm 0 4mm;font-family:DejaVu Serif,serif;font-size:31px;text-transform:uppercase;color:#173f52}.intro{font-family:DejaVu Serif,serif;font-size:13px}.name{margin:3mm 0;font-family:DejaVu Serif,serif;font-size:29px;font-weight:bold;color:{{ $school->primary_color ?: '#167d78' }}}.body{margin:0 auto;max-width:210mm;font-size:13px;line-height:1.7}.formation{display:inline-block;margin-top:2mm;padding:2mm 9mm;border-top:1px solid #b8c6cb;border-bottom:1px solid #b8c6cb;font-size:16px;font-weight:bold;color:#173f52}.facts{margin:5mm auto 0;width:185mm}.fact{display:inline-block;min-width:42mm;padding:0 4mm;border-right:1px solid #d4dde0;font-size:9px;color:#65757d}.fact:last-child{border:0}.fact strong{display:block;margin-top:1mm;font-size:11px;color:#203744}.result{margin-top:4mm;font-size:12px;font-weight:bold}.signature{position:absolute;left:25mm;bottom:15mm;width:65mm;font-size:9px}.sign-line{margin-top:13mm;border-top:1px solid #728188;padding-top:2mm}.verify{position:absolute;right:20mm;bottom:10mm;width:72mm;text-align:left;font-size:8px;color:#66777f}.qr{width:32mm;height:32mm;vertical-align:middle}.verify-copy{display:inline-block;width:46mm;margin-left:3mm;vertical-align:middle}.number{font-family:DejaVu Sans Mono,monospace;font-weight:bold;color:#173f52}.issued{position:absolute;left:103mm;right:103mm;bottom:13mm;font-size:9px;color:#65757d}.contact{position:absolute;left:25mm;right:25mm;bottom:4mm;border-top:1px solid #d7e0e3;padding-top:1.5mm;font-size:7px;color:#78878d}
</style></head><body><div class="page"><div class="outer"><div class="inner"><i class="corner tl"></i><i class="corner tr"></i><i class="corner bl"></i><i class="corner br"></i>
@if($schoolLogo)<img class="logo" src="{{ $schoolLogo }}">@endif
<div class="school">{{ $school->trading_name }}</div>
@if($school->legal_name)<div class="legal">{{ $school->legal_name }}</div>@endif
<div class="kicker">Certification officielle</div><h1>{{ $certificate->type->label() }}</h1><div class="intro">La direction certifie que</div><div class="name">{{ $certificate->student_name }}</div><div class="body">a accompli avec succès le parcours de formation
@if($certificate->formation_name)<br><div class="formation">{{ $certificate->formation_name }} @if($certificate->level) · {{ $certificate->level }} @endif</div>@endif
</div><div class="facts">
@if($certificate->duration_hours)<div class="fact">Volume horaire<strong>{{ $certificate->duration_hours }} heures</strong></div>@endif
@if($certificate->formation_start || $certificate->formation_end)<div class="fact">Période<strong>{{ $certificate->formation_start?->format('d/m/Y') ?? '—' }} – {{ $certificate->formation_end?->format('d/m/Y') ?? '—' }}</strong></div>@endif
@if($certificate->attendance_rate !== null)<div class="fact">Assiduité<strong>{{ number_format((float)$certificate->attendance_rate,1,',',' ') }} %</strong></div>@endif
@if($certificate->group_label)<div class="fact">Groupe<strong>{{ $certificate->group_label }}</strong></div>@endif
</div>
@if($certificate->result)<div class="result">Mention : {{ $certificate->result }}</div>@endif
<div class="signature"><div class="sign-line">{{ $certificate->signature_name ?: 'Direction, signature et cachet' }}</div></div><div class="issued">Délivré le {{ $certificate->issue_date->format('d/m/Y') }}</div><div class="verify"><img class="qr" src="{{ $qrCode }}"><div class="verify-copy"><strong>Document authentifiable</strong><br>Scannez pour vérifier.<br><span class="number">{{ $certificate->certificate_number }}</span></div></div><div class="contact">{{ collect([$school->address_line_1,$school->city,$school->phone,$school->email,$school->website])->filter()->implode(' · ') }}</div></div></div></div></body></html>
