<!doctype html><html lang="fr"><head><meta charset="utf-8"><style>
@page{margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;font-family:DejaVu Sans,sans-serif;color:#17212b;font-size:11px}.page{position:relative;width:172mm;height:250mm;padding:17mm 18mm 15mm;border-top:7mm solid {{ $school->primary_color ?: '#167d78' }};border-bottom:3mm solid #173f52}.header{display:table;width:100%;padding-bottom:9mm;border-bottom:1px solid #ccd8dc}.brand,.contact{display:table-cell;vertical-align:middle}.brand{width:58%}.contact{width:42%;text-align:right;color:#52636d;font-size:9px;line-height:1.65}.logo{max-height:22mm;max-width:38mm;vertical-align:middle;margin-right:5mm}.brand-copy{display:inline-block;vertical-align:middle}.school{font-size:21px;font-weight:bold;color:#173f52}.legal{font-size:9px;color:#64747c}.document{margin-top:14mm;text-align:center}.eyebrow{font-size:9px;text-transform:uppercase;letter-spacing:2px;color:{{ $school->primary_color ?: '#167d78' }}}h1{margin:3mm 0 2mm;font-size:25px;text-transform:uppercase;color:#173f52}.rule{width:22mm;margin:0 auto;border-top:2px solid {{ $school->primary_color ?: '#167d78' }}}.intro{margin:15mm auto 5mm;max-width:155mm;font-size:14px;line-height:1.8}.name{margin:4mm 0 7mm;font-size:24px;font-weight:bold;color:#173f52}.statement{margin:0 auto;max-width:155mm;font-size:13px;line-height:1.9}.details{margin:12mm auto 0;width:155mm;border-collapse:collapse;text-align:left}.details td{padding:3.2mm;border-bottom:1px solid #d7e0e3}.details td:first-child{width:38%;color:#667781}.details td:last-child{font-weight:bold;color:#243844}.mention{margin:8mm auto 0;width:155mm;padding:4mm 5mm;background:#eef6f5;border-left:3px solid {{ $school->primary_color ?: '#167d78' }};font-size:12px}.bottom{position:absolute;left:18mm;right:18mm;bottom:55mm;display:table;width:174mm}.signature,.verify{display:table-cell;vertical-align:bottom}.signature{width:62%;padding-right:12mm}.sign-line{width:62mm;margin-top:8mm;border-top:1px solid #7d8b92;padding-top:2mm;text-align:center;font-size:10px}.verify{width:38%;text-align:right}.qr{width:34mm;height:34mm;vertical-align:middle}.verify-copy{display:inline-block;width:44mm;vertical-align:middle;text-align:left;margin-left:3mm;font-size:8px;color:#64747c}.number{font-family:DejaVu Sans Mono,monospace;color:#173f52;font-weight:bold}.footer{position:absolute;left:18mm;right:18mm;bottom:18mm;padding-top:2.5mm;border-top:1px solid #d7e0e3;text-align:center;color:#6e7c83;font-size:8px}
</style></head><body><div class="page"><div class="header"><div class="brand">@if($schoolLogo)<img class="logo" src="{{ $schoolLogo }}">@endif<div class="brand-copy"><div class="school">{{ $school->trading_name }}</div>@if($school->legal_name)<div class="legal">{{ $school->legal_name }}</div>@endif</div></div><div class="contact">@if($school->address_line_1){{ $school->address_line_1 }}@if($school->city), {{ $school->city }}@endif<br>@endif @if($school->phone)Tél. {{ $school->phone }}<br>@endif @if($school->email){{ $school->email }}<br>@endif @if($school->website){{ $school->website }}@endif</div></div>
<div class="document"><div class="eyebrow">Document officiel</div><h1>{{ $certificate->type->label() }}</h1><div class="rule"></div></div>
<div class="intro">La direction de <strong>{{ $school->trading_name }}</strong> atteste que</div><div class="name">{{ $certificate->student_name }}</div>
@php($action = match($certificate->type->value) {'enrollment_attestation' => 'est régulièrement inscrit(e)', 'attendance_attestation' => 'a participé et satisfait aux exigences de présence', default => 'a suivi le parcours pédagogique prévu'})
<div class="statement">{{ $action }} @if($certificate->formation_name) à la formation <strong>{{ $certificate->formation_name }}</strong>@if($certificate->level), niveau <strong>{{ $certificate->level }}</strong>@endif.@else auprès de notre établissement.@endif</div>
@if($certificate->formation_name || $certificate->formation_start || $certificate->formation_end || $certificate->duration_hours || $certificate->group_label)<table class="details">@if($certificate->formation_name)<tr><td>Formation</td><td>{{ $certificate->formation_name }}</td></tr>@endif @if($certificate->level)<tr><td>Niveau</td><td>{{ $certificate->level }}</td></tr>@endif @if($certificate->group_label)<tr><td>Groupe</td><td>{{ $certificate->group_label }}</td></tr>@endif @if($certificate->formation_start || $certificate->formation_end)<tr><td>Période</td><td>@if($certificate->formation_start)Du {{ $certificate->formation_start->format('d/m/Y') }}@endif @if($certificate->formation_end) au {{ $certificate->formation_end->format('d/m/Y') }}@endif</td></tr>@endif @if($certificate->duration_hours)<tr><td>Volume horaire</td><td>{{ $certificate->duration_hours }} heures</td></tr>@endif @if($certificate->attendance_rate!==null)<tr><td>Taux de présence</td><td>{{ number_format((float)$certificate->attendance_rate,1,',',' ') }} %</td></tr>@endif</table>@endif
@if($certificate->result)<div class="mention"><strong>Mention / résultat :</strong> {{ $certificate->result }}</div>@endif
<div class="bottom"><div class="signature"><div>Délivré à {{ $school->city ?: '________________' }}, le {{ $certificate->issue_date->format('d/m/Y') }}</div><div class="sign-line">{{ $certificate->signature_name ?: 'Direction, signature et cachet' }}</div></div><div class="verify"><img class="qr" src="{{ $qrCode }}"><div class="verify-copy"><strong>Vérification numérique</strong><br>Scannez ce code pour confirmer l’authenticité.<br><span class="number">{{ $certificate->certificate_number }}</span></div></div></div>
<div class="footer">@if($school->registration_number)RC {{ $school->registration_number }} · @endif @if($school->tax_number)NIF {{ $school->tax_number }} · @endif {{ $school->trading_name }} · Document vérifiable en ligne</div></div></body></html>
