<?php
namespace App\Http\Controllers\Admin;
use App\Enums\CertificateType;use App\Enums\ManagementPermission;use App\Http\Controllers\Controller;use App\Models\Certificate;use App\Models\CompanySetting;use App\Models\CourseEnrollment;use App\Models\Student;use App\Services\BadgeQrCode;use Barryvdh\DomPDF\Facade\Pdf;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Gate;use Illuminate\Validation\Rule;use Inertia\Inertia;use Inertia\Response;use Symfony\Component\HttpFoundation\Response as HttpResponse;
class CertificatesController extends Controller
{
 public function index(Request $request):Response {Gate::authorize(ManagementPermission::CERTIFICATES_VIEW->value);$items=Certificate::with(['student:id,first_name,last_name','enrollment.form.course:id,title'])->when($request->filled('type'),fn($q)=>$q->where('type',$request->string('type')))->when($request->filled('search'),function($q)use($request){$s=$request->string('search');$q->where(fn($q)=>$q->where('certificate_number','like',"%{$s}%")->orWhere('student_name','like',"%{$s}%"));})->latest('issue_date')->paginate(20)->withQueryString();return Inertia::render('Admin/Certificates/Index',['certificates'=>$items,'students'=>Student::with(['enrollments'=>fn($q)=>$q->where('status','registered')->with('form.course')])->orderBy('last_name')->get(['id','first_name','last_name']),'types'=>collect(CertificateType::cases())->map(fn($t)=>['value'=>$t->value,'label'=>$t->label()]),'filters'=>$request->only(['search','type'])]);}
 public function store(Request $request):RedirectResponse {Gate::authorize(ManagementPermission::CERTIFICATES_ISSUE->value);$data=$request->validate(['course_enrollment_id'=>['required','exists:course_enrollments,id'],'type'=>['required',Rule::enum(CertificateType::class)],'issue_date'=>['required','date'],'result'=>['nullable','string','max:255'],'signature_name'=>['nullable','string','max:255'],'notes'=>['nullable','string','max:2000']]);$enrollment=CourseEnrollment::with(['student','form.course'])->findOrFail($data['course_enrollment_id']);abort_unless($enrollment->student_id,422);$type=CertificateType::from($data['type']);abort_if($type===CertificateType::DIPLOMA&&!$enrollment->form->course->is_certified,422,'Cette formation ne délivre pas de diplôme.');$attended=$enrollment->student->attendances()->where('course_enrollment_id',$enrollment->id)->whereIn('status',['present','late'])->count();$total=$enrollment->student->attendances()->where('course_enrollment_id',$enrollment->id)->count();$certificate=Certificate::create(['student_id'=>$enrollment->student_id,'course_enrollment_id'=>$enrollment->id,'type'=>$type,'certificate_number'=>'CERT-'.now()->format('Y').'-'.str_pad((string)(Certificate::max('id')+1),6,'0',STR_PAD_LEFT).'-'.str()->upper(str()->random(4)),'verification_token'=>hash('sha256',str()->uuid().str()->random(32)),'issue_date'=>$data['issue_date'],'student_name'=>$enrollment->student->full_name,'formation_name'=>$enrollment->form->course->title,'level'=>$enrollment->level,'group_label'=>$enrollment->group_number?'Groupe '.$enrollment->group_number:null,'duration_hours'=>$enrollment->form->course->duration_hours,'formation_start'=>$enrollment->form->start_date,'formation_end'=>$enrollment->form->end_date,'attendance_rate'=>$total?round($attended/$total*100,2):null,'result'=>$data['result']??null,'signature_name'=>$data['signature_name']??null,'notes'=>$data['notes']??null,'issued_by'=>$request->user()->id]);return back()->with('success',$type->label().' '.$certificate->certificate_number.' généré(e).');}
 public function print(Certificate $certificate,BadgeQrCode $qr):HttpResponse {Gate::authorize(ManagementPermission::CERTIFICATES_PRINT->value);$school=CompanySetting::current();$qrCode='data:image/svg+xml;base64,'.base64_encode($qr->svg($certificate->verification_url,180));$schoolLogo=$this->localImage($school->logo_url);return Pdf::loadView('admin.certificates.print',compact('certificate','school','qrCode','schoolLogo'))->setPaper('a4','landscape')->download($certificate->certificate_number.'.pdf');}
 private function localImage(?string $url):?string {if(!$url)return null;$path=parse_url($url,PHP_URL_PATH);if(!str_starts_with((string)$path,'/storage/'))return null;$file=public_path(ltrim($path,'/'));if(!is_file($file))return null;return 'data:'.(mime_content_type($file)?:'image/png').';base64,'.base64_encode(file_get_contents($file));}
}
