<?php
namespace App\Http\Controllers\Admin;
use App\Enums\ManagementPermission;use App\Http\Controllers\Controller;use App\Models\Classroom;use App\Models\Course;use App\Models\CourseEnrollment;use App\Models\EnrollmentForm;use App\Models\Expense;use App\Models\SalaryStatement;use App\Models\SessionAttendance;use App\Models\Staff;use App\Models\Student;use App\Models\StudentPayment;use App\Models\TrainingPlanGroup;use App\Models\TrainingSession;use Barryvdh\DomPDF\Facade\Pdf;use Illuminate\Http\Request;use Illuminate\Support\Facades\Gate;use Inertia\Inertia;use Inertia\Response;use Symfony\Component\HttpFoundation\StreamedResponse;
class ReportsController extends Controller
{
 private const TYPES=['students'=>'Étudiants','registrations'=>'Inscriptions','formations'=>'Formations','groups'=>'Groupes','attendance'=>'Présences','teachers'=>'Enseignants','employees'=>'Employés','salaries'=>'Salaires','student_payments'=>'Paiements étudiants','expenses'=>'Dépenses','rooms'=>'Salles','sessions'=>'Séances'];
 public function index(Request $request):Response {Gate::authorize(ManagementPermission::REPORTS_VIEW->value);$type=array_key_exists($request->string('type')->toString(),self::TYPES)?$request->string('type')->toString():'students';return Inertia::render('Admin/Reports/Index',['reportType'=>$type,'reportTypes'=>self::TYPES,'rows'=>$this->rows($type,$request),'filters'=>$request->only(['type','date_from','date_to','search'])]);}
 public function export(Request $request,string $format):StreamedResponse|\Symfony\Component\HttpFoundation\Response {Gate::authorize(ManagementPermission::REPORTS_EXPORT->value);$type=array_key_exists($request->string('type')->toString(),self::TYPES)?$request->string('type')->toString():'students';$rows=$this->rows($type,$request);if($format==='pdf')return Pdf::loadView('admin.reports.table',['title'=>self::TYPES[$type],'rows'=>$rows,'from'=>$request->date_from,'to'=>$request->date_to])->setPaper('a4','landscape')->download('rapport-'.$type.'.pdf');return response()->streamDownload(function()use($rows){$out=fopen('php://output','w');fwrite($out,"\xEF\xBB\xBF");if($rows->isNotEmpty())fputcsv($out,array_keys($rows->first()),';');foreach($rows as $row)fputcsv($out,array_map(fn($v)=>is_scalar($v)?$v:json_encode($v),$row),';');fclose($out);},'rapport-'.$type.'.csv',['Content-Type'=>'text/csv; charset=UTF-8']);}
 private function dates($query,Request $r,string $column){return $query->when($r->filled('date_from'),fn($q)=>$q->whereDate($column,'>=',$r->date('date_from')))->when($r->filled('date_to'),fn($q)=>$q->whereDate($column,'<=',$r->date('date_to')));}
 private function rows(string $type,Request $r){$s=$r->string('search')->trim()->toString();$rows=match($type){
 'students'=>$this->dates(Student::query(),$r,'registration_date')->when($s,fn($q)=>$q->where(fn($q)=>$q->where('first_name','like',"%$s%")->orWhere('last_name','like',"%$s%")))->get()->map(fn($x)=>['ID'=>$x->id,'Nom'=>$x->full_name,'Téléphone'=>$x->phone,'Niveau'=>$x->school_level,'Statut'=>$x->status->value,'Inscription'=>$x->registration_date?->format('Y-m-d')]),
 'registrations'=>$this->dates(CourseEnrollment::with('form.course'),$r,'registered_at')->get()->map(fn($x)=>['ID'=>$x->id,'Étudiant'=>trim($x->first_name.' '.$x->last_name),'Formation'=>$x->form->course->title,'Niveau'=>$x->level,'Groupe'=>$x->group_number,'Statut'=>$x->status->value,'Date'=>$x->registered_at?->format('Y-m-d')]),
 'formations'=>$this->dates(EnrollmentForm::with('course'),$r,'start_date')->get()->map(fn($x)=>['ID'=>$x->id,'Formation'=>$x->course->title,'Session'=>$x->title,'Début'=>$x->start_date->format('Y-m-d'),'Fin'=>$x->end_date->format('Y-m-d'),'Actif'=>$x->is_active?'Oui':'Non']),
 'groups'=>TrainingPlanGroup::with(['plan.course','classroom'])->get()->map(fn($x)=>['ID'=>$x->id,'Groupe'=>$x->name,'Formation'=>$x->plan->course->title,'Salle'=>$x->classroom?->name,'Capacité'=>$x->capacity]),
 'attendance'=>$this->dates(SessionAttendance::with(['student','session']),$r,'recorded_at')->get()->map(fn($x)=>['Étudiant'=>$x->student->full_name,'Séance'=>$x->session->title,'Statut'=>$x->status,'Date'=>$x->recorded_at->format('Y-m-d H:i')]),
 'teachers'=>Staff::with('employeeType')->whereHas('employeeType',fn($q)=>$q->where('is_teacher',true))->get()->map(fn($x)=>['Code'=>$x->employee_code,'Nom'=>$x->name,'Téléphone'=>$x->phone,'Statut'=>$x->employment_status->value]),
 'employees'=>Staff::with('employeeType')->get()->map(fn($x)=>['Code'=>$x->employee_code,'Nom'=>$x->name,'Fonction'=>$x->employeeType->name,'Embauche'=>$x->hire_date?->format('Y-m-d'),'Statut'=>$x->employment_status->value]),
 'salaries'=>$this->dates(SalaryStatement::with('staff'),$r,'period_end')->get()->map(fn($x)=>['Référence'=>$x->reference,'Employé'=>$x->staff->name,'Brut'=>$x->gross_salary,'Net'=>$x->net_salary,'Payé'=>$x->amount_paid,'Reste'=>$x->remaining_amount,'Statut'=>$x->status]),
 'student_payments'=>$this->dates(StudentPayment::with(['student','enrollment.form.course']),$r,'payment_date')->get()->map(fn($x)=>['Référence'=>$x->reference,'Étudiant'=>$x->student->full_name,'Formation'=>$x->enrollment->form->course->title,'Montant'=>$x->amount,'Méthode'=>$x->payment_method->label(),'Date'=>$x->payment_date->format('Y-m-d'),'Statut'=>$x->status]),
 'expenses'=>$this->dates(Expense::query(),$r,'expense_date')->get()->map(fn($x)=>['ID'=>$x->id,'Titre'=>$x->title,'Catégorie'=>$x->category,'Montant'=>$x->amount,'Date'=>$x->expense_date->format('Y-m-d'),'Méthode'=>$x->payment_method]),
 'rooms'=>Classroom::all()->map(fn($x)=>['ID'=>$x->id,'Salle'=>$x->name,'Capacité'=>$x->capacity,'Statut'=>$x->is_active?'Active':'Inactive']),
 'sessions'=>$this->dates(TrainingSession::with(['group.plan.course','teacher','classroom']),$r,'starts_at')->get()->map(fn($x)=>['ID'=>$x->id,'Séance'=>$x->title,'Formation'=>$x->group->plan->course->title,'Groupe'=>$x->group->name,'Enseignant'=>$x->teacher?->name,'Salle'=>$x->classroom?->name,'Début'=>$x->starts_at->format('Y-m-d H:i'),'Statut'=>$x->status]),
 default=>collect()};return $s?$rows->filter(fn($row)=>str_contains(strtolower(implode(' ',array_map('strval',$row))),strtolower($s)))->values():$rows;}
}
